### PR TITLE
Renames initialAdminPassword to OPENSEARCH_INITIAL_ADMIN_PASSWORD to be compliant with opensearch naming convention

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Issues Resolved
- Resolves https://github.com/opensearch-project/security/issues/3842

### Testing

- automated tests

### Check List
- [x] New functionality includes testing
~- [ ] New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — CHANGES_REQUESTED** [review]
CI failures for plugin-install look like they need to be addressed `No custom admin password found. Please provide a password.`

**Review by scrawfor99 — APPROVED** [review]

**Review by derek-ho — CHANGES_REQUESTED** [review]
Tests need to be updated

**Comment by DarshitChanpura** [comment]
> CI failures for plugin-install look like they need to be addressed `No custom admin password found. Please provide a password.`

Yes, the file name was updated and hence it failed. CI doing it job :D. I've updated the reference. Feel free to review again.

**Review by peternied — APPROVED** [review]

**Comment by DarshitChanpura** [comment]
Looking into CI failures (seems specific to ubuntu)

**Comment by DarshitChanpura** [comment]
@scrawfor99 would you please reviewing this?

**Review by scrawfor99 — APPROVED** [review]

**Pull request merged**
