### PR TITLE
Updating security reachout email

### PR DESCRIPTION
**Pull request by varun-lodaya**
### Description
[Describe what this change achieves]
Updating security reach out email address from aws-security@amazon.com to security@opensearch.org.

### Issues Resolved
[List any issues this PR will resolve]
N/A

Is this a backport? If so, please add backport PR # and/or commits #
N/A

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]
N/A

### Check List
- [X] New functionality includes testing
- [X] New functionality has been documented
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by shikharj05** [comment]
Thank you! I think this would require changes across packages-

https://github.com/opensearch-project/OpenSearch/blob/main/SECURITY.md
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/SECURITY.md

For better consistency, maybe all other package files can redirect to a single file in this or core package, thoughts?

**Review by willyborankin — APPROVED** [review]

**Comment by varun-lodaya** [comment]
Yes @shikharj05, I have started on this repo but will add similar change across all repos. As for redirection, that's a good idea. The security section can be a reference to 1 common place, maybe at project level. Will wait to hear thoughts from others, @dblock ?

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@shikharj05 could you please fix DCO? (see please https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#developer-certificate-of-origin)

**Comment by cwperks** [comment]
Not sure why DCO failed. The commit is signed off:

```
Signed-off-by: Varun Lodaya <varunml@amazon.com>
```

**Review by cwperks — APPROVED** [review]

**Comment by cwperks** [comment]
Oh, I see the message:

```
Commit sha: [3b091e6](https://github.com/opensearch-project/security/pull/4333/commits/3b091e6b865d37935c1c2615765a98144b075fdb), Author: varun-lodaya, Committer: varun-lodaya; Expected "varun-lodaya [varunml@amazon.com](mailto:varunml@amazon.com)", but got "Varun Lodaya [varunml@amazon.com](mailto:varunml@amazon.com)".
```

Ref: https://github.com/opensearch-project/security/pull/4333/checks?check_run_id=24807243836

I manually set DCO to pass.

**Pull request merged**
