### PR TITLE
rename kibanaserver to dashboardserver

### PR DESCRIPTION
**Pull request by saravanan30erd**
##  opensearch-security pull request intake form
_Please provide as much details as possible to get feedback/acceptance on your PR quickly_

 
 1. __Category: Fix naming convention
 
 

 3. __Description of changes: rename kibanaserver to dashboardserver on internal users

 4. __Why these changes are required? To avoid the name kibana

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by saravanan30erd** [comment]
@peterzhuamazon @TheAlgo  Please review it.

**Comment by davidlago** [comment]
Thanks for the work, @saravanan30erd! Could you please take a look at all the other places where this rename might be needed? [A search here](https://github.com/search?p=9&q=org%3Aopensearch-project+kibanaserver&type=Code) shows that there might be a few places left to address.

**Comment by saravanan30erd** [comment]
@davidlago I think you are searching in current organization repo `https://github.com/search?p=9&q=org%3Aopensearch-project+kibanaserver&type=Code` but the replacement was done in my repo so search should be done in `saravanan30erd/security:fix-name-con`.

However I crosschecked few results from your search, all are replaced.

https://github.com/saravanan30erd/security/blob/fix-name-con/src/main/java/org/opensearch/security/dlic/rest/api/AuditApiAction.java#L74

https://github.com/saravanan30erd/security/blob/fix-name-con/legacy/securityconfig_v6/config.yml#L63

**Comment by saravanan30erd** [comment]
@davidlago  yeah, there are other repos which is having `kibanaserver`. Thought fix it one by one as its managed by multiple teams.

**Review by hardik-k-shah — COMMENTED** [review]
Didn't get chance yet to go through whole PR yet but these changes will require us to handle the migration scenarios. Specially, when someone is migrating to new code base using rolling restart (few nodes running with older configuration of kibanauser and few with newer dashboarduser) as well as full cluster restart (as configuration YML will not be read for existing cluster once setup was already done).

**Comment by peterzhuamazon** [comment]
> Thanks for the work, @saravanan30erd! Could you please take a look at all the other places where this rename might be needed? [A search here](https://github.com/search?p=9&q=org%3Aopensearch-project+kibanaserver&type=Code) shows that there might be a few places left to address.

@davidlago I think there are more changes required in the core of security plugin and its frontend than just renaming a few? Have talked to @cliu123 @hsiang9431-amzn seems like it is a big task to do.

Thanks.

**Comment by davidlago** [comment]
Thanks @peterzhuamazon and @hardik-k-shah. This is a change that we want to plan carefully, as it opens a can of worms with its usage being so pervasive and having to take migrations in to account as well.

@saravanan30erd thanks for the contribution. I will be closing this for now until we have a more solid plan in place that we can review and follow.

**Pull request closed without merging**
