### PR TITLE
Add tracer to Transport

### PR DESCRIPTION
**Pull request by Gaganjuneja**
### Description
Add tracer to fix the breaking issue.

### Issues Resolved
- #3462

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Gaganjuneja** [comment]
@peternied @davidlago @DarshitChanpura Please take a look. Windows backward compatibility is failing, I am not able to find the reason. Please guide me here.

**Comment by Gaganjuneja** [comment]
CC: @reta

**Comment by peternied** [comment]
@Gaganjuneja The windows failures were coming from this IllegalStateException.  Is there a race condition during the start-up process, windows is much 'slower' that the ubuntu builds.  Can you look into this?

```
� ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [securityBwcCluster1-0] uncaught exception in thread [main]
�  org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: Unsupported transport.type [org.opensearch.security.ssl.http.netty.SecuritySSLNettyTransport]
�  	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  Caused by: java.lang.IllegalStateException: Unsupported transport.type [org.opensearch.security.ssl.http.netty.SecuritySSLNettyTransport]
�  	at org.opensearch.common.network.NetworkModule.getTransportSupplier(NetworkModule.java:257) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.node.Node.<init>(Node.java:897) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.node.Node.<init>(Node.java:401) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	... 6 more
```

**Comment by Gaganjuneja** [comment]
> � ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [securityBwcCluster1-0] uncaught exception in thread [main]
> �  org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: Unsupported transport.type [org.opensearch.security.ssl.http.netty.SecuritySSLNettyTransport]
> �  	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  Caused by: java.lang.IllegalStateException: Unsupported transport.type [org.opensearch.security.ssl.http.netty.SecuritySSLNettyTransport]
> �  	at org.opensearch.common.network.NetworkModule.getTransportSupplier(NetworkModule.java:257) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  	at org.opensearch.node.Node.<init>(Node.java:897) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  	at org.opensearch.node.Node.<init>(Node.java:401) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
> �  	... 6 more

Created an issue for this - https://github.com/opensearch-project/security/issues/3464

**Comment by reta** [comment]
> @Gaganjuneja The windows failures were coming from this IllegalStateException. Is there a race condition during the start-up process, windows is much 'slower' that the ubuntu builds. Can you look into this?

@peternied I was trying to reproduce the issue on Windows box locally, sadly no luck, BUT it looks to me this is the issue with distribution: the OS 3.0.0-SNAPSHOT was not yet updated (so no changes in transport) but security plugin tried to use the modified signature - the instantiation fails (which will explain the error)

**Review by reta — APPROVED** [review]

**Review by willyborankin — APPROVED** [review]

**Pull request merged**
