### PR TITLE
Revert "Add ssl script (#1530)"

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
Reverts SSL script to the working version.

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
I've immediately merged this revert to unblock our downstream as quickly as possible.

**Comment by cliu123** [comment]
With the changes in [PR#1530](https://github.com/opensearch-project/security/pull/1530), `install_demo_configuration.sh` scripts exists midway without generating certificates properly. That causes that security plugin could not be installed on OpenSearch. 
If a new PR for these changes will be submitted, please list all testing done in the PR description. All PRs need to make sure at least that CI passes and that security plugin gets built properly and can be installed on corresponding versions of OpenSearch successfully.

**Comment by setiah** [comment]
@cliu123 could you please post the error details and steps to reproduce on this issue? I'd like to take a look.

Reviewing notes from the PR, the existing bash script did not have any automated tests. It was tested manually as mentioned https://github.com/opensearch-project/security/pull/1530#issuecomment-1035694372. Happy to work together on a better process going forward.

**Comment by peternied** [comment]
Please have discussion around an issue in the issue itself, or in a new issue, pull requests comments are easy to lose after the request has been closed out.

**Comment by cliu123** [comment]
We don't have an issue for the regression introduced by the reverted PR. Creating an issue against a PR that has already been reverted might not be confusing.
@setiah If you try installing security plugin 1.3.0.0 on OpenSearch 1.3.0 after running the script `install_demo_configuration.sh`, you'll see the issue. Security plugin cannot be installed correctly.

**Comment by setiah** [comment]
@cliu123 let's take this in https://github.com/opensearch-project/security/issues/1648

>If you try installing security plugin 1.3.0.0 on OpenSearch 1.3.0 after running the script install_demo_configuration.sh

I see some confusion here. The script needs to be run after installing security plugin on OpenSearch (not before). This is consistent with how it worked prior to the changes. I have added the steps for proper installation on the issue. Can you get back with the steps to reproduce the issue as you see it?

**Pull request merged**
