### PR TITLE
[Docs] Add flows for OBO and Service Account

### PR DESCRIPTION
**Pull request by peternied**
### Description
As we are expanding the features in the Security Plugin we are capturing how those features work in our service architecture.  For this set of changes I'm documenting how plugins, extensions with OnBehalfOf tokens, and Extension with service accounts interact with the cluster.

Bonus added a table of contents

### Check List
- [ ] ~New functionality includes testing~
- [X] New functionality has been documented
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
@RyanL1997 @scrawfor99 Would you mind taking a look at this PR, anything you'd like to see updated or changed?

**Review by RyanL1997 — APPROVED** [review]

**Comment by RyanL1997** [comment]
> while supported through the extensions API it needs to be enabled on an individual extension basis and can be revoked at runtime.
@peternied by "revoked" here means the feature itself right? Like the disable option in security config?

**Review by scrawfor99 — DISMISSED** [review]

**Comment by peternied** [comment]
@RyanL1997 I've cleaned up that line, let me know if you think that is an improvement

**Review by DarshitChanpura — APPROVED** [review]
LGTM. Thanks for adding the new doc for execution flows.

**Review by RyanL1997 — APPROVED** [review]
Thanks @peternied, this is looking good to me.

**Pull request merged**
