### PR TITLE
Add conversation indices to install_demo_configuration.sh

### PR DESCRIPTION
**Pull request by HenryL27**
System indices for conversation memory feature going into ml-commons

### Description
Add conversation memory system indices as system indices

### Issues Resolved
ml-commons 1150

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dhrubo-os — APPROVED** [review]

**Review by ylwu-amzn — APPROVED** [review]

**Review by davidlago — CHANGES_REQUESTED** [review]
PR to `main` first please.

**Comment by cwperks** [comment]
@HenryL27 Can you also make the same change to the batch script? https://github.com/opensearch-project/security/blob/main/tools/install_demo_configuration.bat

**Comment by peternied** [comment]
Tried to switch the PR to be against main, didn't take - please rebase this change and change the target of this pull request, or create a fresh pull request against main.

**Comment by HenryL27** [comment]
new PR created to the right place and correct files #3326 . will close this one

**Pull request closed without merging**
