### PR TITLE
[Manual Backport 2.x] Manually backports auth tokens, service accounts, and multi tenancy changes

### PR DESCRIPTION
**Pull request by scrawfor99**
### Description
Manually backports #2716, #2594, and  #2758

PRs  #2716 and #2594 were directly related with the former building off of the latter. 
#2758 is a patch for the failing CI which is required for the CI to pass for this backport. There are a few dependencies on code from #2716 in #2758 so meshing the backports together is probably the most efficient way to move the code. 

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DarshitChanpura** [comment]
Are we backporting extensions and related changes to 2.x?

nit: Can you fix the formatting related changes that were pushed?

**Comment by scrawfor99** [comment]
> 

Yeah, we have to. The changes are aiming for 2.9 latest.

**Comment by peternied** [comment]
@scrawfor99 Can you look into the random failure? Might be related to an issue @willyborankin is looking into

>I played a bit with tests and found out that if you run first TenancyDefaultTenantTests and after that TenancyPrivateTenantEnabledTests the second one will fail in JetBrains. If you re-run tests afterwards they all green. It looks like a bug in the SingleClusterTest class I will try to take a look deeper.

_https://github.com/opensearch-project/security/pull/2557#issuecomment-1531908199_

**Comment by scrawfor99** [comment]
@peternied no problem.

**Comment by willyborankin** [comment]
@scrawfor99 yes 10 seconds tiemouts in some of tests. I checked you branch there is no [fix](https://github.com/opensearch-project/security/pull/2758) in it .

**Comment by willyborankin** [comment]
`TransportUserInjectorIntegTest` is a flaky test. TBH I do not know how to fix it.

**Comment by scrawfor99** [comment]
> `TransportUserInjectorIntegTest` is a flaky test. TBH I do not know how to fix it.

Hi @willyborankin, yeah I know that test is an issue. I am not sure the solution for fixing it off the top of my head either. For the meaintime, this PR should backport your tenancy fix as well my code changes. There were some cross dependencies which made it easier to move things back as a group.

**Pull request merged**
