### PR TITLE
Backports sanity tests to 1.x

### LINKED ISSUE #2398: Backport Sanity test to 1.x branch
Backport sanity tests introduced in #1958.

This change isn't a simple backport as it involves modifying build.gradle as significant changes were made to it moving from 1.x to 2.x.

### PR DESCRIPTION
**Pull request by DarshitChanpura**
Backports #1958 manually.

Resolves #2398 

### Check List
~- [ ] New functionality includes testing~
~- [ ] New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
@DarshitChanpura Looks like this is stuck on some check style issues, want to take another pass at it?

**Review by peternied — CHANGES_REQUESTED** [review]
Unfortunately we can't just backport this PR, the build.gradle scripts were completely rewritten [1]  in 2.0 to fix these issues you are encountering during the build.

Could you see if there a way we can remove the gradle related components of the test so we can minimize build script changes?

- [1] https://github.com/opensearch-project/security/pull/1888

**Comment by DarshitChanpura** [comment]
> @DarshitChanpura any thoughts on where we go from here?

I'll convert this to draft for now until I have significant update.

**Comment by peternied** [comment]
Unless you are actively working on this I'd recommend we covert this to an issue

**Comment by DarshitChanpura** [comment]
> Unless you are actively working on this I'd recommend we covert this to an issue

Done. I will close this PR for now and will re-open once I resume work on this.

**Pull request closed without merging**
