### PR TITLE
add groupId = org.opensearch.plugin

### PR DESCRIPTION
**Pull request by prudhvigodithi**
Signed-off-by: prudhvigodithi <pgodithi@amazon.com>

### Description
Added groupId as org.opensearch.plugin in pluginZip publication

### Issues Resolved
https://github.com/opensearch-project/security/issues/2055

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — DISMISSED** [review]

**Review by cwperks — DISMISSED** [review]

**Comment by prudhvigodithi** [comment]
Hey waiting on for this bug https://github.com/opensearch-project/OpenSearch/pull/4733#issuecomment-1276599104 to be fixed

**Comment by peternied** [comment]
@prudhvigodithi Can we merge this into main, but not backport to 2.X until that issue has been resolved?

**Comment by prudhvigodithi** [comment]
Hey @peternied and @cwperks can you please review again?

**Comment by cwperks** [comment]
@prudhvigodithi Looks like we are having more build failures on the `main` branch after a change of dependencies in `opensearch-rest-client` in core. We get this dependency transitively via `implementation "org.opensearch.client:opensearch-rest-high-level-client:${opensearch_version}"` in the security `build.gradle`

See: [https://github.com/opensearch-project/OpenSearch/commit/4833e080cc506237fee5aa90767d6f49d952bec3#diff-d427b66629707cb1cf8[…]97092af9c5de984b6be6ab4b](https://github.com/opensearch-project/OpenSearch/commit/4833e080cc506237fee5aa90767d6f49d952bec3#diff-d427b66629707cb1cf8e00c15146e9cb0c4a516f97092af9c5de984b6be6ab4b)

Before this is merged we should get a PR out to fix the build breaking change.

**Comment by cwperks** [comment]
See relevant lines in the build output:

```
/home/runner/work/security/security/src/main/java/org/opensearch/security/httpclient/HttpClient.java:34: error: cannot find symbol

import org.apache.http.HttpHeaders;
> Task :compileJava
                      ^
  symbol:   class HttpHeaders
  location: package org.apache.http
/home/runner/work/security/security/src/main/java/org/opensearch/security/httpclient/HttpClient.java:[35](https://github.com/opensearch-project/security/actions/runs/3237632985/jobs/5305275039#step:5:36): error: cannot find symbol
import org.apache.http.HttpHost;
```

**Review by cwperks — APPROVED** [review]

**Review by DarshitChanpura — APPROVED** [review]

**Comment by cwperks** [comment]
@prudhvigodithi Can you rebase this PR with the latest changes from main which includes changes that fix the build?

**Comment by prudhvigodithi** [comment]
Hey @cwperks I have just rebased.
Thank you

**Review by cwperks — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Pull request merged**
