### PR TITLE
Remove redundant isEmpty check and incorrect string equals operator

### PR DESCRIPTION
**Pull request by sujithvm**
##  opensearch-security pull request intake form
_Please provide as much details as possible to get feedback/acceptance on your PR quickly_

 
 1. __Category:__ (_Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation_)
 - Bug
 
 
 2. __Github Issue # or road-map entry, if available:__
- N/A

 3. __Description of changes:__
- Removed redundant `isEmpty` check which is covered by `isNullOrEmpty`
- `escapedKid` cannot be null at the check as it is covered in `isNullOrEmpty` 
- Retaining log line and not publishing any key id in the logs

 4. __Why these changes are required?__ 
- Discovered issue in testing/code scan and recommended to use java equals in place of operator equals 

 5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)
- No change in behavior

 6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manual testing_)
 - Current unit tests are sufficient
 
 
 7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of them_)
- N/A

 8. __Is it backport from main branch?__ (_If yes, please add backport PR # and commits #_)
- No

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by akbhatta — APPROVED** [review]

**Comment by vrozov** [comment]
Please add UT

**Comment by sujithvm** [comment]
> Please add UT

Only functional change is whether log line is generated correctly and what UT is expected for it ?

**Review by mihirsoni — DISMISSED** [review]
LGTM !! Thanks for the changes.

**Comment by vrozov** [comment]
Please add UT for `getVerifiedJwtToken()`. Also, is it necessary to have that logging entry especially at the INFO level?

**Comment by sujithvm** [comment]
@vrozov Testing `getVerifiedJwtToken()` is out of scope for this PR. I m fine with reducing log level to debug

**Comment by vrozov** [comment]
IMO, will be better to remove logging completely (along with the string comparison).

**Comment by sujithvm** [comment]
> IMO, will be better to remove logging completely (along with the string comparison).

Discussed this with @palashhedau @akbhatta and it was decided there is value in keeping the log line

**Comment by vrozov** [comment]
That log entry was never triggered before and nobody complained that the entry is missing, I don't see any value in keeping it.

**Review by vrozov — APPROVED** [review]

**Review by akbhatta — APPROVED** [review]

**Review by palashhedau — APPROVED** [review]

**Pull request merged**
