### PR TITLE
Add script for workflow version increment

### PR DESCRIPTION
**Pull request by RyanL1997**
Signed-off-by: Ryan Liang <jiallian@amazon.com>

### Description
Add script for workflow version increment
* Category (Enhancement)

### Issues Resolved
* Relate: #2352 
* Relate: #2372 

Is this a backport? If so, please add backport PR # and/or commits #
2.x, 2.4

### Check List
- [x] New functionality includes testing
- [ ] ~New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]
Nicely done!

**Comment by cwperks** [comment]
@RyanL1997 Is it possible to accomplish the same version increment automation by adding `.github/workflows/plugin_install.yml` in this block https://github.com/opensearch-project/security/blob/main/build.gradle#L643-L648? I'm wondering if adding a new `ant.replaceregexp` is necessary.

**Comment by RyanL1997** [comment]
> @RyanL1997 Is it possible to accomplish the same version increment automation by adding `.github/workflows/plugin_install.yml` in this block https://github.com/opensearch-project/security/blob/main/build.gradle#L643-L648? I'm wondering if adding a new `ant.replaceregexp` is necessary.

Hi @cwperks, thanks for the comment! I was actually thinking the same yesterday and I found that this line (https://github.com/opensearch-project/security/blob/main/build.gradle#L643) is doing the matching and replacing. It seems like this the content is not the one we want, so I think we may need another `ant.replaceregexp` to specify the content we want for `plugin_install.yml` to match and replace.

**Review by DarshitChanpura — APPROVED** [review]

**Comment by DarshitChanpura** [comment]
@cwperks Can you please merge this once your comment has been resolved?

**Comment by cwperks** [comment]
@RyanL1997 How did you test the change? When I add the file into the existing section and run

```
./gradlew updateVersion -DnewVersion=3.1.0
```

I get the same output when running the change in this PR. The difference is that the first block removes `-SNAPSHOT` and the block in this PR will keep it in.

**Comment by RyanL1997** [comment]
Hi @cwperks, I have updated this and add the workflow directory to the original `ant.replaceregexp `. Here are the screenshots of the local testing:
Screenshot 2023-01-06 at 9 17 41 AM

Screenshot 2023-01-06 at 9 17 00 AM

**Review by cwperks — APPROVED** [review]

**Review by scrawfor99 — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Pull request merged**
