### PR TITLE
[Backport 2.x] Authorize rest requests (#2753) and Enhance RestLayerPrivilegesEvaluator Code Coverage (#3218)

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
Manually Backports #2753 

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DarshitChanpura** [comment]
Waiting for security reviews to be complete before merging.

**Review by peternied — CHANGES_REQUESTED** [review]
Putting the hold on this feature with a request changes requirement - dismissed with the internal reviews have completed

**Comment by scrawfor99** [comment]
What is the status of this PR? Is it meant for 2.9?

**Comment by scrawfor99** [comment]
Removing 2.9 label

**Comment by peternied** [comment]
Based on where the security review for this feature is, it isn't going to make code freeze for 2.10, removing the tag.

**Comment by DarshitChanpura** [comment]
We are targeting 2.11 for this feature and so tagging as such.

**Pull request merged**
