### PR TITLE
[Backport 1.x] Merge remote-tracking branch 'origin/1.3' into 1.x

### PR DESCRIPTION
**Pull request by peternied**
### Description
Merging all updates and improvements from 1.3 into 1.x so its build ecosystem is as robust as 1.3. 

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cwperks** [comment]
```
Error: Exception in thread "main" java.lang.IllegalArgumentException: Plugin [opensearch-security] was built for OpenSearch version 1.4.0 but version 1.3.7 is running
```

The plugin_install workflow will need to be updated for the 1.x branch.

**Comment by peternied** [comment]
```
Error: Exception in thread "main" java.lang.IllegalStateException: failed to load plugin opensearch-security due to jar hell
	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:678)
	at org.opensearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:857)
	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:825)
	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:870)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
Caused by: java.lang.IllegalStateException: jar hell!
class: com.fasterxml.jackson.dataformat.cbor.CBORConstants
jar1: /home/runner/work/security/security/opensearch-1.4.0-SNAPSHOT/lib/jackson-dataformat-cbor-2.14.1.jar
jar2: /home/runner/work/security/security/opensearch-1.4.0-SNAPSHOT/plugins/.installing-10268808545595476024/jackson-dataformat-cbor-2.14.1.jar
	at org.opensearch.bootstrap.JarHell.checkClass(JarHell.java:317)
	at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:212)
	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:676)
	... 11 more
yes: standard output: Broken pipe
```

:(

**Comment by peternied** [comment]
This is blocked on issues with OpenSearch:
- https://github.com/opensearch-project/OpenSearch/issues/5703

**Comment by peternied** [comment]
Using https://tomgregory.com/how-to-exclude-gradle-dependencies/ to help figure out how to exclude the dependencies that are causing trouble...

**Comment by peternied** [comment]
```
Run wget 'https://artifacts.opensearch.org/snapshots/core/opensearch/1.4.0-SNAPSHOT/opensearch-min-1.4.0-SNAPSHOT-windows-x64-latest.zip' --retry-connrefused --tries=3 --no-dns-cache --progress=bar:force:noscroll --verbose
--2023-01-10 23:56:21--  https://artifacts.opensearch.org/snapshots/core/opensearch/1.4.0-SNAPSHOT/opensearch-min-1.4.0-SNAPSHOT-windows-x64-latest.zip
Resolving artifacts.opensearch.org (artifacts.opensearch.org)... 18.164.154.21, 18.164.154.113, 18.164.154.12, ...
Connecting to artifacts.opensearch.org (artifacts.opensearch.org)|18.164.154.21|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-01-10 23:56:21 ERROR 403: Forbidden.
```

Reaching out to the `engineering-effectiveness` team for help

**Comment by peternied** [comment]
@cwperks Could you take another look, here is the diff https://github.com/opensearch-project/security/compare/1.3...peternied:security:1.x

Note, the keyword change is still migrating from 1.x -> 1.3, so that difference is expected

**Review by DarshitChanpura — APPROVED** [review]
LGTM. How should we proceed with WhitSource check failure?

**Review by cwperks — APPROVED** [review]

**Comment by peternied** [comment]
> @DarshitChanpura Lets follow up separately, its impacting other branches as well

**Comment by DarshitChanpura** [comment]
> @DarshitChanpura Lets follow up separately, its impacting other branches as well

Sounds good. I created an issue #2400 to track this. Feel free to modify it.

**Pull request merged**
