### PR TITLE
Remove .opendistro-job-scheduler-lock from list of protected indices (reverts #3237)

### PR DESCRIPTION
**Pull request by scrawfor99**
### Description
- Resolves https://github.com/opensearch-project/job-scheduler/issues/492 , where it was expected that the job schedule index is not protected.

### Check List
- [ ] ~New functionality includes testing~
- [ ] ~New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by willyborankin — APPROVED** [review]

**Review by peternied — CHANGES_REQUESTED** [review]
Why revert, shouldn't this index be secured like the others?

**Review by cwperks — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Comment by scrawfor99** [comment]
@joshpalis and @cwperks are both maintainers of Job Scheduler and said they were in favor of a revert: https://github.com/opensearch-project/job-scheduler/issues/492.

This will be reverted upon run completion.

**Comment by joshpalis** [comment]
@scrawfor99 Would it also be necessary to revert this PR : https://github.com/opensearch-project/job-scheduler/pull/474

**Comment by scrawfor99** [comment]
@joshpalis yeah you should revert the change on your 2.x we are leaving it on main since I assume you still want to go this direction overall

**Pull request merged**
