### PR TITLE
add index, update, delete operation tests

### PR DESCRIPTION
**Pull request by lukasz-soszynski-eliatra**
Signed-off-by: Kacper Trochimiak <kacper.trochimiak@eliatra.com>

### Description
[Describe what this change achieves]
* Category Integration Tests
* Why these changes are required?
* What is the old behavior before changes and new behavior after changes?

The PR adds tests related to the following operations: index, update and delete. Ignored test cases are related to bugs which have been already reported

### Issues Resolved
[List any issues this PR will resolve]

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [x] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — DISMISSED** [review]

**Comment by peternied** [comment]
> Ignored test cases are related to bugs which have been already reported

Could you add the issue next to the @ignore marked tests to make it easy to trace them down?

**Comment by kt-eliatra** [comment]
> > Ignored test cases are related to bugs which have been already reported
> 
> Could you add the issue next to the @ignore marked tests to make it easy to trace them down?

done

**Review by peternied — APPROVED** [review]

**Review by DarshitChanpura — DISMISSED** [review]

**Comment by peternied** [comment]
@lukasz-soszynski-eliatra Can you rebase, this should resolve the build failures that you were previously seeing?

**Comment by lukasz-soszynski-eliatra** [comment]
code rebased into newest main branch

**Review by peternied — APPROVED** [review]

**Review by DarshitChanpura — APPROVED** [review]
Ty @lukasz-soszynski-eliatra !

**Pull request merged**
