### PR TITLE
[Backport 1.3] Update Kafka Client to 3.0.2

### PR DESCRIPTION
**Pull request by vinayak15**
### Description
[Describe what this change achieves]
Update Kafka version to fix security vulnerability(#2095)

### Issues Resolved
[[List any issues this PR will resolve]
](https://github.com/opensearch-project/security/issues/2095)
Is this a backport? If so, please add backport PR # and/or commits #

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — CHANGES_REQUESTED** [review]
Please rebase this change off of main.  We accept changes to main and then backport them as needed, and I think this should follow the standard process.

**Comment by cwperks** [comment]
@peternied This is a manual backport to 1.3. The backport bot failed for 1.3. See https://github.com/opensearch-project/security/pull/2123.

**Comment by peternied** [comment]
Thanks for noticing it was a backport @cwperks I've changed the branch back to 1.3 and as soon as CI finishes we can merge this change (it only requires 1 approver)

**Review by peternied — APPROVED** [review]

**Review by cwperks — APPROVED** [review]

**Comment by peternied** [comment]
I am merging anyways, tests in the `1.3` have many known issues.

**Pull request merged**
