### PR TITLE
v2.12 update roles.yml with new API for experimental alerting plugin feature

### PR DESCRIPTION
**Pull request by AWSHurneyt**
### Description
We added a new API to the alerting plugin to support enhancements to the UI ([link](https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesAction.kt#L13)). The enhancements allow users to configure per query, and per bucket monitors that can query remote clusters via the UI. Previously, such monitors could only be configured using devtools/API commands.

In addition, we added support for configuring cluster metrics monitors which can execute various API ([link to full list of supported API](https://opensearch.org/docs/latest/observing-your-data/alerting/per-cluster-metrics-monitors/#supported-apis)) against remote clusters. The new API is used by the frontend to also support creating these monitors via the UI.

* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation)
  * New experimental feature
  * Enhancement to existing features
* Why these changes are required?
  * To include this API permission in the reserved role that's shipped with the default distribution of OpenSearch.
* What is the old behavior before changes and new behavior after changes?
  * This API was not available before the experimental launch. With the experimental feature enabled, this API can be used to retrieve a list of connect remote clusters, the indexes/aliases on those clusters along with their health statuses, and optionally the mappings for those indexes.

### Issues Resolved
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/796

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
Executed E2E tests with and without the experimental feature enabled to help ensure no regressions.

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by AWSHurneyt** [comment]
Could someone please apply the `backport 2.x`, and `backport 2.12` labels to this PR. I don't seem to have the necessary permissions.

**Review by cwperks — APPROVED** [review]

**Comment by cwperks** [comment]
@AWSHurneyt Should this be added to `alerting_full_access` as well?

**Comment by AWSHurneyt** [comment]
> @AWSHurneyt Should this be added to `alerting_full_access` as well?

Wouldn't the `cluster:admin/opensearch/alerting/*` cover for this API as well?

**Comment by cwperks** [comment]
> Wouldn't the cluster:admin/opensearch/alerting/* cover for this API as well?

Yes it will, disregard my comment. This LGTM. The BWC tests will start passing once https://github.com/opensearch-project/security/pull/4026 is merged

**Review by DarshitChanpura — APPROVED** [review]
@AWSHurneyt Is this targeted for 2.12? if so, to unblock, the feature, would you mind creating the PR against 2.12 branch to avoid delays. The code freeze date is in the past but if this is needed I think we can still get this in with a request.

**Comment by DarshitChanpura** [comment]
@AWSHurneyt could you run this: `node check-permissions-order.js ./config/roles.yml --fix` to fix Code-Hygiene check failure?

**Comment by AWSHurneyt** [comment]
> @AWSHurneyt could you run this: `node check-permissions-order.js ./config/roles.yml --fix` to fix Code-Hygiene check failure?

Revised the PR.

**Comment by AWSHurneyt** [comment]
> @AWSHurneyt Is this targeted for 2.12? if so, to unblock, the feature, would you mind creating the PR against 2.12 branch to avoid delays. The code freeze date is in the past but if this is needed I think we can still get this in with a request.

@DarshitChanpura @cwperks Manual backport to the 2.12 branch
https://github.com/opensearch-project/security/pull/4029

**Review by cwperks — APPROVED** [review]

**Review by DarshitChanpura — APPROVED** [review]

**Pull request merged**
