### PR TITLE
Add action indices:admin/index_template/* to cluster_manage_index_tem…

### LINKED ISSUE #2407: [BUG] Default action group cluster_manage_index_templates should include permissions for composable index templates
**What is the bug?**
The default action group `cluster_manage_index_templates` currently only contains the permission `indices:admin/template/*` for legacy templates. It should also include `indices:admin/index_template/*` to support composable templates.

**How can one reproduce the bug?**
1. Create a role with `cluster_permissions` set to `cluster_manage_index_templates`
2. Create a user with that role
3. Send a PutIndexTemplateRequest to OpenSearch
4. See error `[security_exception] no permissions for [indices:admin/index_template/put]`

**What is the expected behavior?**
Composable templates can be managed by users with `cluster_manage_index_templates` permission.

**What is your host/environment?**
 - 2.4.1

### PR DESCRIPTION
**Pull request by srt**
…plates (#2407)

Signed-off-by: Stefan Reuter <stefan.reuter@reucon.com>

### Description
Adds permissions to manage composable templates to the default action group  `cluster_manage_index_templates`.

### Issues Resolved
#2407 

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — COMMENTED** [review]
@srt Thanks for the contribution, I just started the CI workflow and myself and other maintainers will review your change in detail.

**Review by cwperks — APPROVED** [review]

**Review by peternied — CHANGES_REQUESTED** [review]
Do you know how `cluster:admin/component_template` fits into this space, it seems like it could be related [1], what do you think about including it as well?

- [1] https://opensearch.org/docs/latest/opensearch/index-templates/#composable-index-templates

**Comment by DarshitChanpura** [comment]
I agree with @peternied 's comments above. As `_component_template`s can be used to compose an index template, it might be a good step to include that action here.

**Comment by srt** [comment]
Good point, I have added cluster:admin/component_template/*

**Review by peternied — APPROVED** [review]
Thanks!

**Review by RyanL1997 — APPROVED** [review]

**Pull request merged**
