### PR TITLE
[DRAFT] 2.4 Windows Github Action

### PR DESCRIPTION
**Pull request by scrawfor99**
Basic setup for creating a GitHub Action to run test on push, merge, etc. for Windows.

This is a draft PR and there are several things about it that require further work. Namely: 
- It is not clear how the installation files are fetched when Docker is not used (without Docker being used, cannot call Docker hub)
- The plugin installation process is not successful and the current version makes use of the broken Windows core version where security does not function. 
- The final integration tests are built with Docker in mind so this requires migration. 

### Testing

So far the following functionality has been manually checked on a Windows instance:
1. Enable longer filenames
2. Gradle assemble security 
3. Hardcoded 2.3.0 Snapshot pull (command prompt)
4. Zip extraction and old zip deletion --> The extracted file organization is that of a snapshot so is built for Docker
5. Starting .\bin\opensearch.bat (powershell) --> This currently fails due to bad security plugin install 
6. Curl get https://localhost:9200 -u 'admin:admin' -k -v (command prompt) 
The intermediate steps have not been confirmed to work yet.
### Check List
- [ ] ~New functionality includes testing~
- [X] New functionality has been documented
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
@scrawfor99 It looks like the DCO wasn't signed on one of those commits, could you amend the commit and force push to your branch?

Note; it might be a good time to rebase while you are at it.

**Comment by cwperks** [comment]
> 5. Starting .\bin\opensearch.bat (powershell) --> This currently fails due to bad security plugin install

What error message are you receiving? The available windows distribution does not currently contain the .bat file we're seeking to add with this PR and associated PR that adds the bat file. For development of this action you will need to add the file manually in `plugins\opensearch-security\tools` so its available to be executed.

**Comment by scrawfor99** [comment]
> @scrawfor99 It looks like the DCO wasn't signed on one of those commits, could you amend the commit and force push to your branch?
> 
> Note; it might be a good time to rebase while you are at it.
Took care of this. I must think I accidentally mixed something up before.

**Comment by scrawfor99** [comment]
> > 5. Starting .\bin\opensearch.bat (powershell) --> This currently fails due to bad security plugin install
> 
> What error message are you receiving? The available windows distribution does not currently contain the .bat file we're seeking to add with this PR and associated PR that adds the bat file. For development of this action you will need to add the file manually in `plugins\opensearch-security\tools` so its available to be executed.



> > 5. Starting .\bin\opensearch.bat (powershell) --> This currently fails due to bad security plugin install
> 
> What error message are you receiving? The available windows distribution does not currently contain the .bat file we're seeking to add with this PR and associated PR that adds the bat file. For development of this action you will need to add the file manually in `plugins\opensearch-security\tools` so its available to be executed.

So the original action involves building with gradle but the snapshot that is downloaded from the Windows-team link comes prebuilt so I think the solution is going to be building the security plugin and then move it into the core build instead of trying to build both. I am not sure if this is what you meant but it seems like the best option.

**Pull request closed without merging**
