### PR TITLE
[Backport 1.X] Update tool scripts to run in windows (#2371)

### PR DESCRIPTION
**Pull request by peternied**
### Description
Backport 8ccad5c7d2653fda12acabc1b94afe2b3d9a99dd from #2371

Signed-off-by: Peter Nied <petern@amazon.com>

### Check List
- [ ] New functionality includes testing
- [ ] ~New functionality has been documented~
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cwperks** [comment]
@peternied Has this change been verified on a 1.3 cluster?

**Comment by peternied** [comment]
> @peternied Has this change been verified on a 1.3 cluster?

I've tested `hash.bat` manually on 1.3.7 and it works as expected.

**Comment by peternied** [comment]
Note; I do not plan on rerunning the the CI14 build - it was an intermittent test failure, when #2337 is merged this will be mute.

**Comment by peternied** [comment]
@opensearch-project/security Could I get a review on this change?

**Review by DarshitChanpura — APPROVED** [review]

**Pull request merged**
