### PR TITLE
Updated issue templates from .github.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@dblock.org>

### Description

Coming from https://github.com/opensearch-project/.github/issues/64, updated issue templates for bugs and features.
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]

**Review by peternied — DISMISSED** [review]

**Review by davidlago — APPROVED** [review]

**Comment by davidlago** [comment]
Missing code hygiene check

**Comment by peternied** [comment]
@dblock FYI - I've fixed the line endings issue and pushed that commit to your fork, we will merge this change as soon as CI passes.  Thanks!

**Review by peternied — APPROVED** [review]

**Review by davidlago — APPROVED** [review]

**Comment by dblock** [comment]
I feel like I should fix the line endings in .github ...

**Comment by peternied** [comment]
> I feel like I should fix the line endings in .github ...

@dblock I resolved this in https://github.com/opensearch-project/security/pull/1740/commits/2ad5b14f9871903e1495dde21e45cc5f29406416 which I pushed to your branch before merging.

**Pull request merged**
