### PR TITLE
[Backport 2.x] XContent Refactor

### PR DESCRIPTION
**Pull request by RyanL1997**
### Description

Reacts to refactoring done on xcontent classes from core. Many imports from org.opensearch.common.xcontent were switched to org.opensearch.core.xcontent.

* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation)

Build fix

### Issues Resolved
- Related https://github.com/opensearch-project/OpenSearch/issues/6841
- Related https://github.com/opensearch-project/OpenSearch/pull/6470
- Resolves https://github.com/opensearch-project/security/issues/2588
- Resolves https://github.com/opensearch-project/security/issues/2612 

### Check List
- [ ] ~New functionality includes testing~
- [ ] ~New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by RyanL1997** [comment]
I will look into the test failure introduced by `opensslTest` tmr.

**Comment by RyanL1997** [comment]
I'm updating my findings here: 
Based on the log, it seems like we couldn't setup the openSSL connection correctly. For this error:
```
[ERROR][org.opensearch.security.ssl.http.netty.SecuritySSLNettyHttpServerTransport] Exception during establishing a SSL connection: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f5f6f70656e64697374726f2f5f73656375726974792f73736c696e666f3f70726574747920485454502f312e310d0a486f73743a203132372e302e302e313a31303237340d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a557365722d4167656e743a204170616368652d48747470436c69656e742f342e352e313320284a6176612f31312e302e3138290d0a4163636570742d456e636f64696e673a20677a69702c6465666c6174650d0a0d0a
```
It shows like there is a communication mismatch. I decoded the record, and it gives a `http` request:
```
GET /_opendistro/_security/sslinfo?pretty HTTP/1.1
Host: 127.0.0.1:8628
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.13 (Java/11.0.18)
Accept-Encoding: gzip,deflate
```
I think by enabling the openSSL, we need a `https` request instead. I was checking thru the code base, and I couldn't find the relate changes about this error. I will keep looking for it tmr.

**Comment by peternied** [comment]
I've backported the ClusterManager changes into my fork.  Assuming the test pass https://github.com/peternied/security/actions/runs/4569414539/jobs/8065642541  I think we should merge that into this branch to move forward.

See original source PR
- https://github.com/opensearch-project/security/pull/2062

What do you think @RyanL1997?
FYI: @cwperks @scrawfor99 ?


- https://github.com/opensearch-project/security/pull/2608
- https://github.com/opensearch-project/security/pull/2613

**Comment by RyanL1997** [comment]
I tried to fixed this in the same way as you did, but it didn't work. According to this PR: https://github.com/opensearch-project/OpenSearch/pull/6853, I think they have modified some of the logics on legacy settings. And I'm look into it to see the root cause.

**Review by peternied — APPROVED** [review]

**Pull request merged**
