### PR TITLE
Use GHA `derek-ho/start-opensearch` for OpenSearch plugin install tests

### PR DESCRIPTION
**Pull request by derek-ho**
### Description
This PR uses the externalized start-opensearch action to start opensearch and install the build plugin artifact into it. This was used in security dashboards plugin as well, and decoupling this action was useful as well in case other plugins want to use it themselves. Additionally, this change allows the action to be used with or without security. 

This PR deletes the workflow from the security branch and changes the plugin-install workflow to run using the external action. 

### Issues Resolved
None

Is this a backport? If so, please add backport PR # and/or commits #
No

### Testing
Github actions passing

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by derek-ho** [comment]
Companion PR in the dashboards repo: https://github.com/opensearch-project/security-dashboards-plugin/pull/1783

**Review by willyborankin — DISMISSED** [review]

**Comment by cwperks** [comment]
There are several instances across many repos of Github actions hosted on forks.

Examples:

1. https://github.com/opensearch-project/security/blob/bd3415a63c6bf4ea513543a3c59b88b7be79563f/.github/workflows/automatic-merges.yml#L18
2. https://github.com/opensearch-project/job-scheduler/blob/f453c893a902923bbbc695919219ae0726136aea/.github/workflows/backport.yml#L26
3. https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/gradle-check.yml#L124

I think it makes sense to put these actions in a single repo. One concern I have with actions on forks is that it could produce errors if a fork gets deleted. Do you think its possible to using an existing OpenSearch repo? If not, do you think there's enough justification for creating a new repo to house actions used in repos across the ecosystem?

**Comment by derek-ho** [comment]
> There are several instances across many repos of Github actions hosted on forks.
> 
> Examples:
> 
> 1. https://github.com/opensearch-project/security/blob/bd3415a63c6bf4ea513543a3c59b88b7be79563f/.github/workflows/automatic-merges.yml#L18
> 2. https://github.com/opensearch-project/job-scheduler/blob/f453c893a902923bbbc695919219ae0726136aea/.github/workflows/backport.yml#L26
> 3. https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/gradle-check.yml#L124
> 
> I think it makes sense to put these actions in a single repo. One concern I have with actions on forks is that it could produce errors if a fork gets deleted. Do you think its possible to using an existing OpenSearch repo? If not, do you think there's enough justification for creating a new repo to house actions used in repos across the ecosystem?

I did have this same thought, since it seems like running OpenSearch or OpenSearch Dashboards with or without plugins seems to be common throughout the org. I moved it into my own action to unblock myself for development. I think creating a shared repo may take some time, but I can start looking into the process.

**Comment by derek-ho** [comment]
Maybe we can even use: https://github.com/opensearch-project/.github/tree/main/.github. I will raise a PR contributing the work I have and see how maintainers there feel about this idea.

**Comment by derek-ho** [comment]
https://github.com/opensearch-project/.github/pull/190

**Review by peternied — APPROVED** [review]
Nice!

**Review by RyanL1997 — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Pull request merged**
