### PR TITLE
Revert "Fix 'integTest' not called with test workflows during release…

### PR DESCRIPTION
**Pull request by derek-ho**
… (#4814)"

This reverts commit a1816fb020867b2af6732d3915115af7771b0fb9.

### Description
[Describe what this change achieves]
* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation)
* Why these changes are required?
* What is the old behavior before changes and new behavior after changes?

### Issues Resolved
[List any issues this PR will resolve]

Is this a backport? If so, please add backport PR # and/or commits #, and remove `backport-failed` label from the original PR.

Do these changes introduce new permission(s) to be displayed in the static dropdown on the front-end? If so, please open a draft PR in the security dashboards plugin and link the draft PR here

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] New Roles/Permissions have a corresponding security dashboards plugin PR
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md)
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by cwperks — APPROVED** [review]

**Comment by reta** [comment]
Sorry @derek-ho , why it is reverted?

**Review by RyanL1997 — APPROVED** [review]

**Comment by cwperks** [comment]
> Sorry @derek-ho , why it is reverted?

Tests with the `integTest` task should run against a cluster configured by opensearch-build and the `integrationTest` task of the security plugin spins up in-memory test clusters.

The `integTest` task is trigged by release tests to run against a release candidate with all plugins installed. 

@derek-ho I think this PR should also add back in the `integtest.sh` file from https://github.com/opensearch-project/security/pull/3844/files#diff-7c96c1263d98396b99fc05f50f3c1282760df88d08a220f7a878d97ebe8cb1db

**Comment by reta** [comment]
Superseded by https://github.com/opensearch-project/security/pull/4866?

**Comment by cwperks** [comment]
> Superseded by #4866?

Yes, this can be closed. @reta Please see my replies to Nils' comments on https://github.com/opensearch-project/security/pull/4866

**Pull request closed without merging**
