### PR TITLE
Changes affected String.toString() method calls to reflect correct signature

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
Fixes broken CI

* Category: Maintenance
* Why these changes are required? To get CI working again

### Issues Resolved
- #2417 
- #2420

### Testing
Manual testing

### Check List
~- [ ] New functionality includes testing~
~- [ ] New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DarshitChanpura** [comment]
CI task failures because Maven artifact for opensearch-3.0.0-SNAPSHOT is not updated with latest changes.

**Review by scrawfor99 — COMMENTED** [review]
Overall looks good to me. 

My only question is whether we are generally fine with the System.out.prints in the test files. I know you didn't put them there but I don't know what we think about those being part of the tests when I assume they are left from debugging--the asserts are the real tests.

**Comment by peternied** [comment]
> CI task failures because Maven artifact for opensearch-3.0.0-SNAPSHOT is not updated with latest changes.

Is there an issue for this, seems like this is blocking our CI time and time again.

**Comment by scrawfor99** [comment]
> > CI task failures because Maven artifact for opensearch-3.0.0-SNAPSHOT is not updated with latest changes.
> 
> Is there an issue for this, seems like this is blocking our CI time and time again.

I think there is sometimes an issue filed for a specific build but there is not one for the pattern. I am not sure what kind of issue you would do for that/where you would put it.

**Comment by DarshitChanpura** [comment]
> > CI task failures because Maven artifact for opensearch-3.0.0-SNAPSHOT is not updated with latest changes.
> 
> Is there an issue for this, seems like this is blocking our CI time and time again.

https://github.com/opensearch-project/security/issues/2276 seems related to this

**Comment by peternied** [comment]
> #2276 seems related to this

@DarshitChanpura That bug is in our repository - I don't think we are activity trying to fix it, please create an issue in OpenSearch so they can start engaging.

**Comment by DarshitChanpura** [comment]
> > #2276 seems related to this
> 
> @DarshitChanpura That bug is in our repository - I don't think we are activity trying to fix it, please create an issue in OpenSearch so they can start engaging.

Done. https://github.com/opensearch-project/OpenSearch/issues/6061

**Comment by DarshitChanpura** [comment]
CI job failure looks related to https://github.com/opensearch-project/security/issues/2248. But i'm not sure why is it affecting only 11 build and for mac-os only. Looking into it now

**Comment by DarshitChanpura** [comment]
Test failure is related to https://github.com/opensearch-project/security/issues/2229

**Review by RyanL1997 — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Pull request merged**
