### PR TITLE
Backport cluster evaluation permissions #1885 to 2.0

### PR DESCRIPTION
**Pull request by rutuja-amazon**
### Description
Backport of #1885 to 2.0

### Issues Resolved
Backport PR #1885  

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]

**Review by peternied — CHANGES_REQUESTED** [review]
Looks like backporting this change will not be a one-off process, please fix the build/test failures so this can be reviewed.

**Comment by rutuja-amazon** [comment]
@peternied thanks a lot, I'm working on fixing the issues.

**Comment by peternied** [comment]
@rutuja-amazon It looks like the build is passing now, but there are some other CI failures that need to be addressed, please make updates for those and then we can see about getting this approved and merged, thanks!

**Comment by rutuja-amazon** [comment]
@peternied I have fixed the CI issues and all other checks had been passing as well, we can merge post the all the checks pass for the new changes.

**Review by peternied — APPROVED** [review]
Thanks, looks good to merge!

**Pull request merged**
