### PR TITLE
[Backport 2.x] React to changes in ActionListener in core

### PR DESCRIPTION
**Pull request by RyanL1997**
### Description
Manual backport for #3153 of React to changes in ActionListener in core
Also includes a fix for a call to XContentHelper.toXContent in response to https://github.com/opensearch-project/OpenSearch/pull/9156
### Issues Resolved
* Relate https://github.com/opensearch-project/OpenSearch/pull/9352
* Relate #3153 

### Check List
- [ ] ~New functionality includes testing~
- [ ] ~New functionality has been documented~
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by cwperks — APPROVED** [review]

**Review by willyborankin — APPROVED** [review]

**Comment by peternied** [comment]
Looks like this was required because we've got those Clean up REST API changes in main that haven't been pulled into 2.x [1] - and likely won't until the set of changes is complete.

- [1] https://github.com/opensearch-project/security/pull/2900

**Comment by peternied** [comment]
@cwperks It looks like the codeql build task is broken because of a cached version of the snapshot - should we disable the gradle build cache on our github actions?  Is this something we've been doing manually

**Comment by cwperks** [comment]
@peternied any idea how much disabling caching would slow down the CI? I am in favor of disabling it because it has been making our builds unpredictable.

**Comment by peternied** [comment]
@cwperks I'll take a slower correct over a fast and incorrect any day.  I'll create a PR

**Comment by cwperks** [comment]
Why is codeql running `./gradlew compileIntegrationTestJava` on 2.x? 

> Task :compileIntegrationTestJava FAILED

**Comment by peternied** [comment]
> Why is codeql running ./gradlew compileIntegrationTestJava on 2.x?

@cwperks Good find, can you create an issue and make sure this is all unified between 2.x and main?

**Comment by peternied** [comment]
@RyanL1997 FYI - I just merged in the change to disable the gradle build cache, we should expect all builds to pass prior to merging.

Note; We don't require codeql. so lets follow up separately if that is busted

**Pull request merged**
