### PR TITLE
Update Dependency Versions:  Woodstox 6.4.0, Scala-lang 2.13.9, Jackson-Databind 2.14.0

### PR DESCRIPTION
**Pull request by scrawfor99**
Signed-off-by: Stephen Crawford <steecraw@amazon.com>

### Description
Fixes a remaining dependency to Woodstox 6.2.6 library as a follow-up to https://github.com/opensearch-project/security/pull/2197. I incorrectly looked at only the direct dependencies previously not accounting for the transient dependencies introduced by other libraries. This force should make the Woodstox version match the desired 6.4.0. 

I also corrected the versions for jackson_databind, kafka, and snakeyaml. 

### Issues Resolved
Further resolves the Woodstox dependency problem. 

### Testing 
After the change, runnning `./gradlew dependencies` shows all references to Woodstox-core being bumped to 6.4.0 and all the other WhiteSource issues being fixed. 

### Check List
- [x] New functionality includes testing
- [] ~New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by scrawfor99** [comment]
@cwperks @DarshitChanpura this build failure does not seem related to the changes made in this commit. What do you guys think?

**Comment by DarshitChanpura** [comment]
I was just going through the test failures and I agree

**Comment by DarshitChanpura** [comment]
I've triggered a re-run to see if it was one-off failure, cause most of the tests are failing due to `Address already in use` error

**Comment by cwperks** [comment]
@DarshitChanpura 1.3 build is known to be flaky - https://github.com/opensearch-project/security/issues/2023

It may take a couple of retries.

**Comment by DarshitChanpura** [comment]
okay.. do we want to proceed with merge @cwperks ?

**Comment by cwperks** [comment]
@DarshitChanpura Let's make sure this PR and the one against 1.x match. I don't think we need `snakeyaml` listed in here and we may not need netty in the section either, but I'd like to wait for an updated SNAPSHOT from core and then re-run the CI to see what version of netty it would resolve to without forcing the resolution strategy. If we need to force the resolution strategy than that is fine, but it would be nice to have a mechanism to know when there is a version mismatch with the version in core's version.properties.

**Comment by cwperks** [comment]
Actually this can be done locally as well.

If you checkout version 1.3 of core locally and run the following:

```
./gradlew assemble
./gradlew publishToMavenLocal
```

once those are complete switch to the patch for 1.3 of security and run

```
./gradlew clean assemble
```

That should produce a .zip in `build/distributions`

From there you check what jars are included for snakeyaml and netty.

**Comment by DarshitChanpura** [comment]
@scrawfor99 Were you able to test the behavior with the steps @cwperks mentioned?

**Comment by scrawfor99** [comment]
@DarshitChanpura, no because I cannot use my Mac (1.3 does not work on M1) to test it and I am getting errors trying to create a new remote desktop currently. I tried two different accounts and various settings with no avail so am going to table it for now. It should not be too big a change either way once it is testable.

**Comment by scrawfor99** [comment]
Update: I am away for the remainder of the day for travel but I will be confirming this works tomorrow and updating accordingly. I did set up a linux remote desktop to test this.

**Review by CEHENKLE — DISMISSED** [review]

**Review by cwperks — APPROVED** [review]

**Comment by cwperks** [comment]
Confirmed via creating a local snapshot of the latest from 1.3 of core and publishing to maven local. It is not necessary to force the netty resolution as it will resolve to the version of netty from core. This will make maintenance easier because it will not require an update every time core updates the netty dependency.

**Comment by cwperks** [comment]
@scrawfor99 Thank you for looking into CI stability on the 1.3 branch. Can you do the manual backport and test to see if it improves CI stability for 1.3?

**Review by cwperks — APPROVED** [review]

**Comment by scrawfor99** [comment]
@cwperks thank you for rerunning the failures as needed until things passed. I looked into the issue and the backport is complicated. I suspect that is why it did not happen in the first place. I am going to create an issue for the changes to be backported. After resolving the basic issues with the backport I encountered a problem where the new logic expects to be able to find various files in `auditlog/` however I do not think this folder exists in the earlier version.

**Pull request merged**
