### PR TITLE
Updates DlsFlsFilterLeafReader to use new Lucene document() instead of visitDocument()

### LINKED ISSUE #2353: [AUTOCUT] OS Distribution Build Failed for security-3.0.0
***Received Error***: **Error building security, retry with: ./build.sh manifests/3.0.0/opensearch-3.0.0.yml --component security**.
                      The distribution build for security has failed.
                      Please see build log at https://build.ci.opensearch.org/job/distribution-build-opensearch/6718/consoleFull

### PR DESCRIPTION
**Pull request by scrawfor99**
### Description
Updates the DlsFlsFilterLeafReader to use the new Lucene StoredFiltersReader document() syntax. 

### Issues Resolved
Resolves #2353 2353

### Testing
Updated localMaven and compileJava run. 

### Check List
- [ ] ~New functionality includes testing~
- [ ] ~New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by scrawfor99** [comment]
Looks like this is going to break the bwcTests.

**Review by cwperks — APPROVED** [review]

**Comment by cwperks** [comment]
> Looks like this is going to break the bwcTests.

Is the HEAD of 2.x building or facing the same issue? Would the bwc tests work if this change was merged into 2.x first?

**Comment by cwperks** [comment]
@scrawfor99 I will file an issue so we can discuss how to include a PRs changes when running the BWC test suite. It will only reflect a PR's backwards compatibility after the PR has been merged...

This change looks good to me. @opensearch-project/security Can we get a second review? This change will unblock the distribution build.

**Comment by cwperks** [comment]
@scrawfor99 Filed on issue on the deficiency in the `backward-compatibility` check: https://github.com/opensearch-project/security/issues/2365

**Review by davidlago — APPROVED** [review]

**Review by RyanL1997 — APPROVED** [review]

**Comment by cwperks** [comment]
Merging without required checks as they are flaky or due to an issue outside of this PR. See https://github.com/opensearch-project/security/pull/2366 for passing checks with this change and BWC performed with the changes in this branch.

**Comment by DarshitChanpura** [comment]
@scrawfor99 Should we create a follow-up to address test failures or will it solved in this PR?

**Comment by cwperks** [comment]
@DarshitChanpura See comments, an issue has been created and a PR is out to address the issues with the `backward-compatibility` check

**Pull request merged**
