### PR TITLE
Update non java files

### PR DESCRIPTION
**Pull request by scrawfor99**
### Description
Updates the code style for everything that is not a java file. 

### Check List
- [ ] ~New functionality includes testing~
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@scrawfor99 :clap:  looks pretty good, this is the same rules as for OpenSearch core, right?

**Review by cwperks — APPROVED** [review]
@reta I think this was taken from job-scheduler but it looks very similar to core to me:

- JS: https://github.com/opensearch-project/job-scheduler/blob/main/gradle/formatting.gradle
- core: https://github.com/opensearch-project/OpenSearch/blob/main/gradle/formatting.gradle

**Comment by cwperks** [comment]
@scrawfor99 Please open up a manual backport of this change to 2.x.

**Comment by scrawfor99** [comment]
> @scrawfor99 Please open up a manual backport of this change to 2.x.

I was just gonna backport the style changes manually once everything is approved if that is okay. Basically, I am intentionally splitting the changes so they can be reviewed but for the backport we can just run the new workflow to backport.

**Comment by cwperks** [comment]
@scrawfor99 There may be some challenges in backporting other PRs if its in a state where there are formatting changes on main that are not in the 2.x branch. I think it may make sense to backport these individually or do one big PR with all formatting changes.

**Comment by scrawfor99** [comment]
Hi @cwperks, the reason the formatting changes are split like this is to try and make reviewing the changes feasible. Basically, there are too many changes to be reviewed altogether so it is easier to tell how things are changing by moving piece by piece. 

The issue with backporting each individual PR is that we are not actually backporting a code change but just an updated format guideline. What we would want to backport is just the build.gradle change not the actual code changes resulting from the the updated formatting themselves. 

I am not sure how to do that so I am hoping we can instead just update the format of the entirety of 2.x once we have all accepted the changes as appropriate. 

Does that make sense?

**Pull request merged**
