### PR TITLE
fix #13 fix for : DLS overrides broader permissions

### LINKED ISSUE #13: DLS overrides broader permissions
Assume `user1` has two roles (assume they are `admin` and `read_index1_dls`).

The `admin` role grants `UNLIMITED` permissions on `*` indices. The `read_index1_dls` role grants `READ` permissions on `index1`, but also restricts this user from seeing certain documents in `index1` through a DLS query.

It would be expected that the user would have access to all documents in `index1` through the `admin` role, however actual behavior is that the DLS query is applied, and `user1` is unable to read documents that the DLS query filters.

As a side note, the [search-guard documentation](https://docs.search-guard.com/latest/document-field-level-security) (see section Multiple roles and document-level security) states:

> A user can be member of more than one role, and each role can potentially define a different DLS query for the same index. In this case, all DLS queries are collected and combined with OR.

So this actually might be expected behavior, however it is not "correct" from a usability standpoint, IMO.

### PR DESCRIPTION
**Pull request by chrousto**
##  opendistro-for-elasticsearch/security pull request intake form
_Please provide as much details as possible to get feedback/acceptance on your PR quickly_
This PR fixes the issue #13 that describes how a user with :

1. one or more role that has some DLS configuration for document filtering 
2. one or more role with no DLS filtering (i.e. has access to everything)

still sees only the conjunction of DLS restriction instead of the conjunction of DLS + everything = everything.
 
 1. __Category:__ (_Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation_)
 Bug fix
 
 
 2. __Github Issue # or road-map entry, if available:__
#13

 3. __Description of changes:__
The idea of the change is to position a dummy __dlsfullaccess__ string inside the DLS object, this way when the whole map is parsed, if this string is found, all other entry are cleared for the specified index pattern.

 4. __Why these changes are required?__ 
This is a a bug the behavior of the plugin does not reflect what has been configured.

 5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)
```bash
##############################
Create internal user ...

{
  "status" : "CREATED",
  "message" : "'my_user' created."
}

##############################
Create 'regular' role with dls on index 'my_index' ...

{
  "status" : "CREATED",
  "message" : "'my_role1' created."
}

##############################
Map 'regular' role with dls filtering on index my_index ...

{"status":"CREATED","message":"'my_role1' created."}
##############################
Create 'admin' (all access) role without dls filtering ...

{
  "status" : "CREATED",
  "message" : "'my_admin_role_without_dls_match_all' created."
}

##############################
Map 'admin' (all access) role without dls filtering ...

{"status":"OK","message":"'my_admin_role_without_dls_match_all' updated."}
##############################
Get authinfo ...

{
  "user" : "User [name=my_user, backend_roles=[], requestedTenant=null]",
  "user_name" : "my_user",
  "user_requested_tenant" : null,
  "remote_address" : "[::1]:55724",
  "backend_roles" : [ ],
  "custom_attribute_names" : [ ],
  "roles" : [
    "my_role1",
    "own_index",
    "my_admin_role_without_dls_match_all"
  ],
  "tenants" : {
    "my_user" : true
  },
  "principal" : null,
  "peer_certificates" : "0",
  "sso_logout_url" : null
}

##############################
Get my_index data ...

{
  "took" : 86,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 2.0,
    "hits" : [
      {
        "_index" : "my_index",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 2.0,
        "_source" : {
          "field1" : "value1"
        }
      }
    ]
  }
}

```
Here the user should see more fields. 
~~I will provide more data/scripts to test against from within the PR.~~
I have provided proper test units from within the PR

 6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manual testing_)
 The testing has, for the moment, been done only with custom script, I have yet to familiarize myself with the testing framework provided with the code.
 
 
 7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of them_)
Not that I know or can think of.

 8. __Is it backport from main branch?__ (_If yes, please add backport PR # and commits #_)
No

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by cliu123** [comment]
Thanks for contributing! Can you add Unit Tests?

**Comment by cliu123** [comment]
> Thanks for contributing! Can you add Unit Tests?

@chrousto Thanks for adding UTs for the PR819! Please let us know once the UTs are ready for this PR.

**Comment by chrousto** [comment]
> > Thanks for contributing! Can you add Unit Tests?
> 
> @chrousto Thanks for adding UTs for the PR819! Please let us know once the UTs are ready for this PR.

Hey @cliu123 , 
I am in the process of writing UTs for this one too.
I will update you asap.

**Comment by rursprung** [comment]
i think this is the same as i reported in #1572 (sorry, didn't spot your ticket at the time) and the solution for that has just been merged (see #1735).

**Comment by davidlago** [comment]
Thanks for the connection, @rursprung! Closing this PR.

**Pull request closed without merging**
