### PR TITLE
[Part 1] Replace JUnit assertEquals() with Hamcrest matchers assertThat()

### PR DESCRIPTION
**Pull request by EduardoCorazon**
### Description
This is a new PR based on: https://github.com/opensearch-project/security/pull/3443 

This change is a response to opensearch-project/security issue https://github.com/opensearch-project/security/issues/1832 whereby it's recommended to replace Assert.assertEquals(...) with assertThat(...) for a greater degree of verbosity.

Upon collaboration, this PR will try to address and refactor files to use assertThat() as prompted in https://github.com/opensearch-project/security/pull/3443#pullrequestreview-1655814270

- Refactoring
- Using the Hamcrest matchers with assertThat() yields clearer failure messages for testing.
- The old behavior uses assertEquals() which is part of the Assert class in JUnit meanwhile the new method, assertThat(), belongs to the Hamcrest class which tends to be more human readable.

### Issues Resolved
- Addressed security issue https://github.com/opensearch-project/security/issues/1832
- Will address files in https://github.com/opensearch-project/security/pull/3443#pullrequestreview-1655814270 

Is this a backport? If so, please add backport PR # and/or commits #
backport 2.x

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DarshitChanpura** [comment]
Screenshot 2023-10-09 at 11 11 28 AM

@EduardoCorazon Seems like there are lot more occurrences for `assertEquals`

**Comment by EduardoCorazon** [comment]
@DarshitChanpura I will definitely get to working on them! I just made this new PR to fix some things on my end. I want to make sure that each full file replacement of assertEquals() works before working on the next. I already have two more commits to push but I'm trying to figure out why this simple replacement is failing CI tests.

**Comment by DarshitChanpura** [comment]
@EduardoCorazon The backwards compatibilty tests will pass once https://github.com/opensearch-project/security/pull/3498 is merged

**Comment by DarshitChanpura** [comment]
@EduardoCorazon I've marked this as draft. Please mark it as ready for review once all changes are complete.

**Comment by EduardoCorazon** [comment]
I apologize for the delayed action on this draft. I can't believe it did not occur to me to just use regular expressions 😅

**Comment by DarshitChanpura** [comment]
@EduardoCorazon What do you think about splitting this PR into two parts? I see that you are halfway there with about 80 files left. This would allow the changes to be manageable while reviewing.

**Comment by EduardoCorazon** [comment]
@DarshitChanpura that's a great idea! Let me quickly push this last change before splitting.

**Comment by EduardoCorazon** [comment]
ready to go

**Comment by DarshitChanpura** [comment]
@EduardoCorazon There are some outstanding file conflicts. I'll review once you address them

**Comment by EduardoCorazon** [comment]
@DarshitChanpura After talking with Stephen it seems that separating it into parts might be causing the issues since the changes affect important files. As such, a possible solution would be to submit all changes in a single PR but this would make reviewing changes a bit tedious. However, I don't think I will have enough time to finish replacing the remaining files before the end of the program. I deeply apologize for the length of time I've taken to address this issue and for my lack of efficiency in such an approach. I've submitted a new issue with a little bit of notes and recommendations since the original issue is from 2022. If possible, I will try my best to keep contributing to the repo even after the end of the program if that's ok. Again I deeply apologize.

**Pull request closed without merging**
