### PR TITLE
[Backport 1.3] Staging for version increment automation

### PR DESCRIPTION
**Pull request by peternied**
Backport 235d25672139c0663b422c3f7a2354e0250f23b0 from #1932

Note; had to remove BWC related changes since they were not included until 2.0 of this codebase

### CODE REVIEW

**Comment by peternied** [comment]
I think that CI isn't going to work with this change, keeping this out there if we want to avoid cutting PRs like https://github.com/opensearch-project/security/pull/2028#pullrequestreview-1072859419

**Comment by prudhvigodithi** [comment]
Hey @peternied this worked I have tested with branch `backport/backport-1932-to-1.3`, by executing the task `./gradlew updateVersion -DnewVersion=1.3.5-SNAPSHOT`. But I see `fileset(dir: projectDir)` was included with empty set of files, and a separate line was added for `buid.gradle` file, I see from the [past PR](https://github.com/opensearch-project/security/pull/2028) we need to update the version at 2 places in build.gradle file `opensearch_version = System.getProperty("opensearch.version", "1.3.5-SNAPSHOT")` and `securityPluginVersion`, so how about you add the task following.
```
task updateVersion {
    onlyIf { System.getProperty('newVersion') }
    doLast {
        ext.newVersion = System.getProperty('newVersion')
        println "Setting version to ${newVersion}."
        // String tokenization to support -SNAPSHOT
        ant.replaceregexp(match: opensearch_version.tokenize('-')[0], replace: newVersion.tokenize('-')[0], flags:'g', byline:true) {
            fileset(dir: projectDir) {
                     include(name: 'build.gradle')
            }
        }
    }
} 
```

Or something like the following being explicit 
```
        ant.replaceregexp(file:'build.gradle', match: "securityPluginVersion = '\\d.*'", replace: '"securityPluginVersion = "' + newVersion.tokenize('-')[0] + '.0"', flags:'g', byline:true)
        ant.replaceregexp(file:'build.gradle', match: '"opensearch.version", "\\d.*"', replace: '"opensearch.version", "' + newVersion.tokenize('-')[0] + '-SNAPSHOT"', flags:'g', byline:true)
  ```

**Comment by prudhvigodithi** [comment]
Hey @peternied any update on this, one of the [workflow](https://github.com/opensearch-project/opensearch-build/actions/runs/2967596360) [job](https://github.com/opensearch-project/opensearch-build/runs/8124405545?check_suite_focus=true) failed as this task updateVersion is not part of 1.3 branch.
@bbarani @gaiksaya

**Comment by prudhvigodithi** [comment]
Hey @peternied can you please post an update, without this task the the next version of the security repo is not happening. For 1.3.6 the increment has to be done manually 
Thank you
@zelinh @bbarani

**Comment by cwperks** [comment]
@peternied I am unable to re-run CI for this PR. Does this PR (https://github.com/opensearch-project/security/pull/2001) need to be backported to 1.3?

**Comment by peternied** [comment]
> @peternied I am unable to re-run CI for this PR. Does this PR (#2001) need to be backported to 1.3?

No - permissions are set to the repository, not on individual branches.  I am also unable to re-run the job - but its moot because the failure in `build-artifact-names` needs to be resolved

**Review by DarshitChanpura — APPROVED** [review]

**Comment by peternied** [comment]
Note, I bypassed CI checks because there were stuck on random failures, CI passed on 2/3 platforms already

**Pull request merged**
