### PR TITLE
Revert "backport cluster evaluation permissions #1885 to `opendistro-1.11`"

### PR DESCRIPTION
**Pull request by rutuja-amazon**
Reverts opensearch-project/security#1986
### Description
Reverts backport of #1885 to `opendistro-1.11` - this was causing unforeseen changes on the managed service end. 

### Issues Resolved
Backport PR #1885  

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
Why revert this whole change instead of fixing the build break?

**Comment by rutuja-amazon** [comment]
@peternied  There are two classes `RestHelper` and `IndexTemplateClusterPermissionsCheckTest` that have issues - `RestHelper` needed a lot of functionality to be added in the back-port and the import paths in this version are different than the later versions. This would need refactoring on classes like `ClusterInfo`, etc. which will require additional work. If we can revert the changes now - since this is urgently blocking managed service changes, I can re-raise a new PR with required refactoring for backport post this version getting stabilised.

**Review by cliu123 — APPROVED** [review]

**Comment by rutuja-amazon** [comment]
There is `SSLHandshakeException` causing CI failure.

**Comment by peternied** [comment]
After much consideration and discussion the branch that is being targeted `opendistro-1.1*` is unsupported, and this code is being used and maintained by a private fork.  Rather than gate changes to a fork, it makes more sense for that repository to diverge in the areas its supporting but this repository are not supporting.  This avoids having to wait on the security maintainers to review / approve / merge changes - doubly so when these changes cannot be validated by the CI systems in GitHub associated with them.

I am closing out this pull request and the other related pull requests, seperately we will consider how we want to address these branches that are no longer supported, in other OpenSearch Project components the ODFE versions of the codebases were archived whereas this one was copied with all its issues.

**Pull request closed without merging**
