### PR TITLE
Remove master keywords

### PR DESCRIPTION
**Pull request by cliu123**
### Description
[Describe what this change achieves]
* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation) Refactoring

### Issues Resolved
https://github.com/opensearch-project/security/issues/1664

### Testing
ITs

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cliu123** [comment]
> https://github.com/opensearch-project/security/blob/main/config/checkstyle/sun_checks.xml#L204

The check cannot be enabled as some `master` keyword referencing to OpenSearch core, for example `node.master`.
`Whitelist` is not going to be reomoved until OpenSearch 3.0.

**Comment by cliu123** [comment]
> > The check cannot be enabled as some master keywords referencing to OpenSearch core, for example node.master.
> 
> Shouldn't we be able to switch to something like `node.cluster_manager`? We should be able to remove all of the 'master' based language from this codebase, or its a bug on OpenSearch.

`node.cluster_manager` is not a valid configuration in OpenSearch core.

**Comment by peternied** [comment]
> node.cluster_manager is not a valid configuration in OpenSearch core.

If this is the case, we should have bugs on OpenSearch because our migration effort is blocked.

To keep this effort moving could you create issues on any OpenSearch blockers and then use checkstyle exclusion comments so we can merge the progress that you've made while we chase down these outstanding items.  What do you think of this?

**Comment by cliu123** [comment]
@peternied I've listed out the items that we cannot change in [the OpenSearch issue](https://github.com/opensearch-project/OpenSearch/issues/472#issuecomment-1157933857) and [the security plugin issue](https://github.com/opensearch-project/security/issues/1664#issuecomment-1157932397). So we can unblock this PR.

**Comment by davidlago** [comment]
Could you please create a follow-up issue in our repo to come back and update the missing ones you reported in https://github.com/opensearch-project/OpenSearch/issues/472#issuecomment-1157933857 once they get addressed?

**Comment by cliu123** [comment]
> Could you please create a follow-up issue in our repo to come back and update the missing ones you reported in [opensearch-project/OpenSearch#472 (comment)](https://github.com/opensearch-project/OpenSearch/issues/472#issuecomment-1157933857) once they get addressed?

I've created a separate issue to track the changes in Java APIs when OpenSearch core is ready: https://github.com/opensearch-project/security/issues/1887

**Review by davidlago — APPROVED** [review]

**Pull request merged**
