### PR TITLE
Bump version 2.5.0

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
Bumps version to 2.5.0-SNAPSHOT

Created manually as auto-cut PR: https://github.com/opensearch-project/security/pull/2210 doesn't contain all changes.

### Check List
~- [ ] New functionality includes testing~
~- [ ] New functionality has been documented~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]
Nice work!

**Review by peternied — APPROVED** [review]
Feel free to merge when you've got it passing CI

**Comment by cwperks** [comment]
@DarshitChanpura When should `security` be added to the 2.5.0 build manifest? The `security-dashboards-plugin` cannot be version incremented without `security` being in the manifest and having SNAPSHOT artifacts for 2.5.0.

**Comment by DarshitChanpura** [comment]
> @DarshitChanpura When should `security` be added to the 2.5.0 build manifest? The `security-dashboards-plugin` cannot be version incremented without `security` being in the manifest and having SNAPSHOT artifacts for 2.5.0.

Hmm.. I was under the impression they automatically added it for all back-end plugins. Nevertheless, I have created https://github.com/opensearch-project/opensearch-build/pull/2931 to add it to 2.5.0 manifest

**Pull request merged**
