### PR TITLE
Proxy authentication tests

### PR DESCRIPTION
**Pull request by lukasz-soszynski-eliatra**
Signed-off-by: Lukasz Soszynski <lukasz.soszynski@eliatra.com>

### Description
[Describe what this change achieves]
* Category (Integration tests)
* Why these changes are required?
* What is the old behaviour before changes and new behaviour after changes?

Integration tests related to proxy authentication added

### Issues Resolved
[List any issues this PR will resolve]

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by DarshitChanpura — CHANGES_REQUESTED** [review]
Ty @lukasz-soszynski-eliatra ! One request, could you please add a brief javadoc for all the new classes that you have added in this PR. Would be super helpful down the line.

**Comment by lukasz-soszynski-eliatra** [comment]
Done

**Comment by lukasz-soszynski-eliatra** [comment]
Done

**Review by DarshitChanpura — DISMISSED** [review]

**Comment by DarshitChanpura** [comment]
Bwc tests are broken on main. Tracking issue here: https://github.com/opensearch-project/security/issues/2221

**Review by peternied — DISMISSED** [review]

**Review by cwperks — APPROVED** [review]

**Comment by DarshitChanpura** [comment]
@lukasz-soszynski-eliatra Looks like there are some merge conflicts. Can you please resolve them?

**Comment by lukasz-soszynski-eliatra** [comment]
Done, conflicts resolved :)

**Review by cwperks — APPROVED** [review]

**Pull request merged**
