### PR TITLE
Added index search privilege to a security analytics full access role

### PR DESCRIPTION
**Pull request by stevanbz**
Signed-off-by: Stevan Buzejic <buzejic.stevan@gmail.com>

### Description
[Describe what this change achieves]
* Enhancement
* New index privilege has been added in order to security analytics full access role
* Users with security analytics full access role can create detectors on indices

### Issues Resolved
https://github.com/opensearch-project/security-analytics/issues/182

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cwperks** [comment]
@stevanbz Can you rebase this with the latest from main and have the CI run again? Main was unstable yesterday due to an upstream change in Lucene and has since been fixed.

**Comment by stevanbz** [comment]
> @stevanbz Can you rebase this with the latest from main and have the CI run again? Main was unstable yesterday due to an upstream change in Lucene and has since been fixed.
Done! Tnx!

**Review by RyanL1997 — APPROVED** [review]

**Comment by cwperks** [comment]
Thank you @stevanbz, can you provide an explanation on how this change resolves the linked issue?

By giving mapping a user to the `security_analytics_full_access` role it will be giving them permission to query all indices with this change.

The only other reserved role that gives `indices:data/read/search*` is the `asynchronous_search_full_access` role.

**Comment by stevanbz** [comment]
> Thank you @stevanbz, can you provide an explanation on how this change resolves the linked issue?
> 
> By giving mapping a user to the `security_analytics_full_access` role it will be giving them permission to query all indices with this change.
> 
> The only other reserved role that gives `indices:data/read/search*` is the `asynchronous_search_full_access` role.

Good point. I'll be back with the answer just to think a little bit. Tnx for constructive comment

**Comment by stevanbz** [comment]
> > Thank you @stevanbz, can you provide an explanation on how this change resolves the linked issue?
> > By giving mapping a user to the `security_analytics_full_access` role it will be giving them permission to query all indices with this change.
> > The only other reserved role that gives `indices:data/read/search*` is the `asynchronous_search_full_access` role.
> 
> Good point. I'll be back with the answer just to think a little bit. Tnx for constructive comment

Just discussed with team member and after some analysis - I agree with you. I will decline the PR - it's not appropriate to add a privilege to search all indices

**Pull request closed without merging**
