### PR TITLE
Remove sleep when waiting for node close

### PR DESCRIPTION
**Pull request by peternied**
### Description
For each node in the cluster we were removing and then sleeping for
250ms.  There is an API that we can wait on to be sure the node has
closed or at least take action if the closure wasn't successful.

For the usage, which is cleaning up all nodes, switching to a best
effort mode that could wait the same 250ms or return faster.

### Testing
~Tested in this PR's workflow, new runtime is 25 minutes down from 40, a 40% reduction in runtime.~
Tested in this PR's workflow, new runtime is 25 minutes, seeing this amount of time hit during other runs.  While it might not provide a giant boost, I still think its worthwhile to avoid unreasoned sleeps.

### Check List
- [ ] ~New functionality includes testing~
- [ ] ~New functionality has been documented~
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by DarshitChanpura — APPROVED** [review]

**Comment by peternied** [comment]
@cliu123 Could I get a review on this pull request?

**Comment by peternied** [comment]
@opensearch-project/security Could I get a second review?

**Comment by cliu123** [comment]
> @cliu123 Could I get a review on this pull request?

Sorry, I missed this message.

**Comment by cliu123** [comment]
LGTM!

**Review by cliu123 — APPROVED** [review]

**Pull request merged**
