### PR TITLE
Add parameters to authorize index_global_state restore

### PR DESCRIPTION
**Pull request by ashangit**
##  opendistro-for-elasticsearch/security pull request intake form
_Please provide as much details as possible to get feedback/acceptance on your PR quickly_

 
 1. __Category:__ Enhancement
 
 
 
 2. __Github Issue # or road-map entry, if available:__

 3. __Description of changes:__

Add possibility to authorize snapshot restore with index global state

 4. __Why these changes are required?__ 

Needed to restore templates, ILM and ilm state on index when restoring indices

 5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)

index_global_state is just not authorized

 6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manual testing_)
 
 
 
 7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of them_)

 8. __Is it backport from main branch?__ (_If yes, please add backport PR # and commits #_)

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by dblock** [comment]
Looks good, could use tests. Looks like we don't have any unit tests for `SnapshotRestoreEvaluator` but don't let that stop you?

**Comment by dblock** [comment]
Thanks for adding tests! Will get this reviewed.

**Review by peternied — CHANGES_REQUESTED** [review]
@ashangit if you still interested in seeing this change merged, we can get it unblocked.

* Since you made these changes we are requiring appending DCO sign off on all commits [more details](https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#developer-certificate-of-origin), could you rebase and sign off?

* The other element that is missing is exercising the new setting with the snapshot api tests in [SnapshotRestoreTests.java](https://github.com/opensearch-project/security/blob/918d9989d36a4c3b3d8bafc69dac6abe4345e7b9/src/test/java/org/opensearch/security/SnapshotRestoreTests.java).

What do you think?

**Comment by cliu123** [comment]
Closing for inactivity.
@ashangit Thanks for the PR! The repo has been moved to OpenSearch. We would love to review the PR. Please feel free to re-open the PR when you get chance to finalize it and get it ready for review.

**Pull request closed without merging**
