### PR TITLE
Set security plugin 3.0.0 baseline JDK version to JDK-21

### PR DESCRIPTION
**Pull request by reta**
### Description
Set security plugin 3.0.0 baseline JDK version to JDK-21

* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation)
* Why these changes are required?
* What is the old behavior before changes and new behavior after changes?

### Issues Resolved
Closes https://github.com/opensearch-project/security/issues/4407

### Testing
N/A

### Check List
- [X] New functionality includes testing
- [X] New functionality has been documented
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by willyborankin — DISMISSED** [review]

**Comment by reta** [comment]
Seems like the GA cannot be changed at the same time as JDK baseline, opening https://github.com/opensearch-project/security/pull/4461

**Comment by reta** [comment]
Needs https://github.com/derek-ho/start-opensearch/pull/6

**Review by willyborankin — APPROVED** [review]

**Comment by reta** [comment]
@peternied @cwperks @scrawfor99 folks could you please help to review? there are changes in Github branch checks that needs this pull request in. Thank you.

**Review by cwperks — APPROVED** [review]

**Comment by cwperks** [comment]
@reta I'm not able to re-run the CI checks that are stuck. You may need to push a change to get the CI checks to re-run.

**Comment by reta** [comment]
> @reta I'm not able to re-run the CI checks that are stuck. You may need to push a change to get the CI checks to re-run.

Yes, taking to @gaiksaya , thanks @cwperks !

**Comment by willyborankin** [comment]
> @reta I'm not able to re-run the CI checks that are stuck. You may need to push a change to get the CI checks to re-run.

They were created by me in PR which I closed. I'm wondering why they appeared in all PR :-)

**Comment by reta** [comment]
> They were created by me in PR which I closed. I'm wondering why they appeared in all PRs :-)

These checks are configured in repo settings, asked to remove them for now

**Comment by willyborankin** [comment]
> > @reta I'm not able to re-run the CI checks that are stuck. You may need to push a change to get the CI checks to re-run.
> 
> They were created by me in PR which I closed. I'm wondering why they appeared in all PRs :-)
I got it why.

**Comment by willyborankin** [comment]
> > They were created by me in PR which I closed. I'm wondering why they appeared in all PRs :-)
> 
> These checks are configured in repo settings, asked to remove them for now

We do not need them. It was an experiment.

**Pull request merged**
