### PR TITLE
Re-enables CrossClusterSearchTests

### LINKED ISSUE #3425: [Test] CrossClusterSearchTests are flaky
### Description
It looks like the cross cluster setup that evolves multiple clusters coming online and communicating with one another have issues that make them fragile.

### Repo
1. Go to `src/integrationTest/java/org/opensearch/security/CrossClusterSearchTests.java`
2. Find the `@Ignore` entry on the class
3. Delete that attribute
4. Run the tests with `./gradlew integrationTest --tests org.opensearch.security.CrossClusterSearchTests`

### Exit Criteria
- [ ] Find the root cause of the failing cluster startup process
- [ ] Run the test at least 10 times and see no failures - [how to do this](https://github.com/opensearch-project/security/pull/3388/commits/a714cf5cd07c0fa624965ab0b1a7c34e5143b75e)

### PR DESCRIPTION
**Pull request by EduardoCorazon**
### Description
This change addresses an issue that can arise when setting up two clusters at the same time whereby, port mismatches can occur as outlined in issue #3425. However, after much testing this issue does not appear to be tied to this integration test or it could be related to a windows environment issue.

* Category: Test fix
* Why these changes are required? : No changes are to be merged except the removal of @ignore given the findings of this tests. The integration test for CrossClusterSearchTests appears to have been fixed with unrelated changes to the main branch. 
* What is the old behavior before changes and new behavior after changes? : All the changes listed below except remove the commit that removes @ignore stemmed from an error on my end [please dismiss it] due to an issue in my working branch. However, it seems that the original issue might have been caused by the working environment or some other related factor. But, after verifying tests run correctly, the issue appears to be fully resolved. [ Verification: https://github.com/EduardoCorazon/security/actions/runs/6679334900]

### Issues Resolved
#3425 

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
View attached exit criteria

### Exit Criteria
- [ ] Find the root cause of the failing cluster startup process [still unsure]
 - [x] Run the test at least 10 times and see no failures - [how to do this](https://github.com/opensearch-project/security/pull/3388/commits/a714cf5cd07c0fa624965ab0b1a7c34e5143b75e)

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by DarshitChanpura — COMMENTED** [review]
@EduardoCorazon Since this test was flaky originally (hence @ignore) could you please verify that the flakiness has been resolved by making multiple CI runs (similar to what you did in the last run)?

**Comment by EduardoCorazon** [comment]
@DarshitChanpura certainly. After running multiple CI runs I believe the test flakiness has been resolved. Should I attach screenshots or something similar of that nature to this pr?

**Comment by peternied** [comment]
@EduardoCorazon For one of the steps, quoted below, you'd include that change to 'mutliplex' out the number of test runs from normal 1 out to 10, then a link to the github action workflow on your fork would make it easy for some like like myself to quickly take a look and give the 👍 on this change.  Could you include a link here so we can verify?

> Run the test at least 10 times and see no failures - [how to do this](https://github.com/opensearch-project/security/pull/3388/commits/a714cf5cd07c0fa624965ab0b1a7c34e5143b75e)

**Comment by EduardoCorazon** [comment]
@peternied certainly! Thank you for the clarification! Just to double check, is this what you're referring to? https://github.com/EduardoCorazon/security/actions/runs/6634226075

**Review by DarshitChanpura — COMMENTED** [review]
Thank you @EduardoCorazon. Can you help me understand why creating a variable instead of inline arguments resolves the flakiness?

**Review by peternied — COMMENTED** [review]
I'm happy to approve and merge the removal of the `@ignore` anotation, maybe the tests were never an issue or maybe they have trouble working correctly in a windows environment.

For the other changes - I don't think they are making a material difference, unless there is something that I'm missing?

**Comment by EduardoCorazon** [comment]
@DarshitChanpura @peternied I do not believe the test were the issue as running them seems to work fine without any kind of change. However, based on my testing, the flakiness was resolved when lists of pairs were saved as variables and then referenced instead of being passed as arguments directly. But this was due to issues in the branch I was working on (hence why I switched over to main just to be safe).

### Original Issue
As per why the code changes resolved my issue, I'm not too sure since I was receiving: `Execution failed for task :integrationTest. No tests found for given includes: [**/*$*.class, ...]` . Which also resulted in an 'empty' index.html file in `/build/reports/tests/integrationTest/index.html`. Furthermore, I was unable to find a meaningful connection when running gradlew integration tests with `--debug`, so my insights into the exact error is very limited. Hence, (perhaps out of lack of options) I decided to try and fix the warning in vscode: `Type safety: A generic array of Pair<String,String> is created for a varargs parameter` and it turned out that fixed the flakiness. 

### Suggestion?
Upon reflection, I do not think the code change has any meaningful impact assuming the error was indeed due to some mistake on my branch, and if you'd like I can remove it?

**Comment by EduardoCorazon** [comment]
@peternied I've removed the added code, edited the response on this pr, and now the only difference from the original is the removal of `@ignore`. While I'm still unsure of what caused the original issue, I will make sure my future contributions have more depth and detail to them. Many apologies and thank you for your patience and guidance!

**Review by peternied — APPROVED** [review]

**Pull request merged**
