### PR TITLE
Removes unused get/post/put cache endpoint

### PR DESCRIPTION
**Pull request by derek-ho**
### Description
Removes Get, Post, Put cache API routes, since only delete is used. This should not be backported to 2.x, and we should add a deprecation notice there as well (although these were never used anyway so the behavior should be consistent)

### Issues Resolved
[List any issues this PR will resolve]

Is this a backport? If so, please add backport PR # and/or commits #, and remove `backport-failed` label from the original PR.

Do these changes introduce new permission(s) to be displayed in the static dropdown on the front-end? If so, please open a draft PR in the security dashboards plugin and link the draft PR here

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] New Roles/Permissions have a corresponding security dashboards plugin PR
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md)
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by derek-ho** [comment]
@DarshitChanpura how do we mark this as deprecated in the 2.x line? Just add a Java annotation @Deprecated?

**Review by willyborankin — DISMISSED** [review]

**Comment by cwperks** [comment]
@derek-ho We can use the DeprecationLogger and add a warning to the API response if someone calls the endpoint with one of the deprecated verbs.

**Comment by willyborankin** [comment]
@derek-ho couofl you please fix `Code Hygiene / Spotless scan (pull_request) Failing` ?

**Review by RyanL1997 — APPROVED** [review]

**Review by peternied — DISMISSED** [review]

**Review by cwperks — APPROVED** [review]

**Comment by cwperks** [comment]
@derek-ho Can you also raise a PR against the API specification repo to reflect this change?

ref: https://github.com/opensearch-project/opensearch-api-specification/blob/main/spec/namespaces/security.yaml#L449-L498

**Review by peternied — APPROVED** [review]

**Comment by cwperks** [comment]
Merging this into main. @derek-ho please open a backport with the deprecation messages discussed above.

**Pull request merged**
