### PR TITLE
Switch from RC1 to the GA of OpenSearch 2.0

### PR DESCRIPTION
**Pull request by peternied**
### Description
Switch from RC1 to the GA of OpenSearch 2.0

### Issues
* Resolves https://github.com/opensearch-project/security/issues/1823

### Check List
- [ ] ~New functionality includes testing~
- [ ] ~New functionality has been documented~
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
This change won't work as is because the 2.0.0 build of OpenSearch has not been uploaded to maven, we are blocked until this has occurred.

**Review by DarshitChanpura — APPROVED** [review]

**Comment by peternied** [comment]
Note, this is blocked on https://github.com/opensearch-project/opensearch-build/pull/2100

**Review by DarshitChanpura — DISMISSED** [review]

**Comment by peternied** [comment]
Note, I'm looking into a consistent failure with remote re-indexing

**Comment by peternied** [comment]
> Note, I'm looking into a consistent failure with remote re-indexing

Latest change (https://github.com/opensearch-project/security/pull/1826/commits/1d8ae2589ca689f49c6030a44b80fe01a1f84ade) resolves this issue, the document type filter should have been removed completely during the last set of changes

**Review by cliu123 — CHANGES_REQUESTED** [review]
Please update all the versions in `bwc-test/build.gradle`.

**Comment by peternied** [comment]
> Please update all the versions in `bwc-test/build.gradle`.

@cliu123 this is done, thanks for spotting

**Review by DarshitChanpura — APPROVED** [review]

**Review by cliu123 — APPROVED** [review]

**Pull request merged**
