### PR TITLE
Incremented version to 2.1.1.

### PR DESCRIPTION
**Pull request by gaiksaya**
Coming from https://github.com/opensearch-project/opensearch-build/issues/1818 post release activities.

### CODE REVIEW

**Review by cliu123 — APPROVED** [review]

**Review by DarshitChanpura — APPROVED** [review]

**Comment by DarshitChanpura** [comment]
@cwperks Looks like this failed due to netty version mismatch. Could this be related to the netty issue that you were working on?
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> Could not resolve all dependencies for configuration ':testRuntimeClasspath'.
Downloading https://repo.maven.apache.org/maven2/com/fasterxml/jackson/module/jackson-modules-java8/2.13.3/jackson-modules-java8-2.13.3.pom to /home/runner/.gradle/.tmp/gradle_download11647884912109613000bin
   > Conflict(s) found for the following module(s):
       - io.netty:netty-transport-native-unix-common between versions 4.1.79.Final and 4.1.76.Final
     Run with:
         --scan or
         :dependencyInsight --configuration testRuntimeClasspath --dependency io.netty:netty-transport-native-unix-common
     to get more insight on how to solve the conflict.
```

**Comment by cliu123** [comment]
CI fails.
@cwperks Do you happend to have context on this error about `io.netty:netty-transport-native-unix-common`?
```
2022-07-13T23:57:23.2312393Z FAILURE: Build failed with an exception.
2022-07-13T23:57:23.2312608Z 
2022-07-13T23:57:23.2312750Z * What went wrong:
2022-07-13T23:57:23.2313106Z Execution failed for task ':test'.
2022-07-13T23:57:23.2314152Z > Could not resolve all dependencies for configuration ':testRuntimeClasspath'.
2022-07-13T23:57:23.2314900Z Downloading https://repo.maven.apache.org/maven2/com/fasterxml/jackson/module/jackson-modules-java8/2.13.3/jackson-modules-java8-2.13.3.pom to /home/runner/.gradle/.tmp/gradle_download11647884912109613000bin
2022-07-13T23:57:23.2315867Z    > Conflict(s) found for the following module(s):
2022-07-13T23:57:23.2316507Z        - io.netty:netty-transport-native-unix-common between versions 4.1.79.Final and 4.1.76.Final
2022-07-13T23:57:23.2316809Z      Run with:
2022-07-13T23:57:23.2317016Z          --scan or
2022-07-13T23:57:23.2317491Z          :dependencyInsight --configuration testRuntimeClasspath --dependency io.netty:netty-transport-native-unix-common
2022-07-13T23:57:23.2317883Z      to get more insight on how to solve the conflict.

**Comment by cwperks** [comment]
@DarshitChanpura This is related to the netty upgrade, but its an issue with transitive dependencies of another dependency. 

See the output below of running: 

```
./gradlew :dependencyInsight --configuration testRuntimeClasspath --dependency io.netty:netty-transport-native-unix-common

io.netty:netty-transport-native-unix-common:4.1.79.Final
+--- io.netty:netty-handler:4.1.79.Final
|    +--- org.opensearch.plugin:transport-netty4-client:2.1.1-SNAPSHOT:20220713.234733-3
|    |    \--- testRuntimeClasspath
|    \--- org.apache.zookeeper:zookeeper:3.7.1 (requested io.netty:netty-handler:4.1.76.Final)
|         \--- testRuntimeClasspath
\--- org.opensearch.plugin:transport-netty4-client:2.1.1-SNAPSHOT:20220713.234733-3 (*)

io.netty:netty-transport-native-unix-common:4.1.76.Final -> 4.1.79.Final
+--- io.netty:netty-transport-classes-epoll:4.1.76.Final
|    \--- io.netty:netty-transport-native-epoll:4.1.76.Final
|         \--- org.apache.zookeeper:zookeeper:3.7.1
|              \--- testRuntimeClasspath
\--- io.netty:netty-transport-native-epoll:4.1.76.Final (*)
```

Looking into resolutions now.

**Comment by cliu123** [comment]
@gaiksaya Please rebase this branch against 2.1 branch when https://github.com/opensearch-project/security/pull/1945 gets backported to 2.1 branch. Thanks!

**Comment by gaiksaya** [comment]
@peternied Waiting for this https://github.com/opensearch-project/security/pull/1947 to merge to 2.1 since the base branch is 2.1

**Comment by peternied** [comment]
@gaiksaya I should have been reviewing PRs in the other order, #1947 has been merge.  You should be unblocked

**Comment by gaiksaya** [comment]
Hey! looks like code-ql workflow is failing with below error:
```
  Error: ref 'refs/heads/increment-to-2.1.1' not found in this repository
  RequestError [HttpError]: ref 'refs/heads/increment-to-2.1.1' not found in this repository
```

**Pull request merged**
