### PR TITLE
add .plugins-ml-config in the system index

### PR DESCRIPTION
**Pull request by Zhangxunmt**
### Description
[Describe what this change achieves]
* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation)
New feature

* Why these changes are required?
.plugins-ml-config is the new system index required to store encryption key.

* What is the old behavior before changes and new behavior after changes?
Old behavior does not meet the bar from the app sec team. The new method based on this system index is recommended. 

### Issues Resolved
[List any issues this PR will resolve]

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by cwperks — DISMISSED** [review]

**Comment by cwperks** [comment]
@Zhangxunmt Is this targeting 2.9?

**Comment by Zhangxunmt** [comment]
@cwperks , Yes this is targeting for 2.9 release.

**Review by willyborankin — DISMISSED** [review]

**Comment by cwperks** [comment]
@Zhangxunmt Can you confirm if integ tests with security have been run with this change included in each plugin that relies on the index? 

k-nn previously had issues when adding system index protection that was caught in their integ tests. You can see discussion on [here](https://github.com/opensearch-project/security/pull/2480) and the revert in 2.6 happened in this [commit](https://github.com/opensearch-project/security/commit/766cf3f713fb7621faa8546ca5c2f37f5a847009)

**Review by scrawfor99 — DISMISSED** [review]
This is good but will need the dependency versions forced. @cwperks opened a backport PR directly against 2.9 for you in the meantime.

**Review by RyanL1997 — DISMISSED** [review]

**Comment by Zhangxunmt** [comment]
https://github.com/opensearch-project/security/pull/2996, this change is included in this PR.

**Review by cliu123 — DISMISSED** [review]

**Comment by cwperks** [comment]
@Zhangxunmt Can you please re-base this PR with main?

This PR was included directly into 2.9 in this [PR](https://github.com/opensearch-project/security/pull/2996), but still needs to be merged into main and 2.x

**Comment by Zhangxunmt** [comment]
This PR can be closed, since it was included in the earlier PR? @cwperks

**Comment by cwperks** [comment]
@Zhangxunmt This PR still needs to be merged into main and 2.x. If you rebase this PR we can merge it to main and have backport bot create a PR for 2.x

**Comment by Zhangxunmt** [comment]
@cwperks rebase finished. Can you approve?

**Review by cwperks — APPROVED** [review]

**Review by cliu123 — APPROVED** [review]

**Comment by RyanL1997** [comment]
Re-running the flaky windows bwc test

**Review by RyanL1997 — APPROVED** [review]

**Comment by Zhangxunmt** [comment]
@cwperks the rebase is successful and no conflicts. Can you pls merge the PR?

**Pull request merged**
