### PR TITLE
Add tracer for getHttpTransports

### PR DESCRIPTION
**Pull request by RyanL1997**
### Description
[Describe what this change achieves]
* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation)
Maintenance

### Issues Resolved
* Relate https://github.com/opensearch-project/OpenSearch/pull/9415

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Review by cwperks — APPROVED** [review]

**Comment by RyanL1997** [comment]
Looking into the bwc failure now

**Review by scrawfor99 — APPROVED** [review]

**Comment by RyanL1997** [comment]
After 5 times re-run on the task of plugin install for windows runner, it is still failing on the connection issue:
```
Run peternied/action-sleep@v1
Run Start-Sleep -s 30
Run $credentialBytes = [Text.Encoding]::ASCII.GetBytes("admin:admin")
Invoke-WebRequest: D:\a\_temp\cebbf9a0-1544-42d9-ac73-cebfa0841e9f.ps1:6
Line |
   6 |  Invoke-WebRequest -SkipCertificateCheck -Uri 'https://localhost:9200/ …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No connection could be made because the target machine actively refused it.

Error: Process completed with exit code 1.
```

**Comment by peternied** [comment]
The error logs indicate there is a bug preventing the server from coming up:

```
Error: 9-08T21:50:21,330][ERROR][o.o.b.Bootstrap          ] [smoketestnode] Exception
java.lang.IllegalStateException: Unsupported http.type [org.opensearch.security.http.SecurityHttpServerTransport]
	at org.opensearch.common.network.NetworkModule.getHttpServerTransportSupplier(NetworkModule.java:240) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.node.Node.newHttpTransport(Node.java:1757) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.node.Node.<init>(Node.java:911) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.node.Node.<init>(Node.java:[400](https://github.com/opensearch-project/security/actions/runs/6126464757/job/16631275359?pr=3338#step:8:413)) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:[404](https://github.com/opensearch-project/security/actions/runs/6126464757/job/16631275359?pr=3338#step:8:417)) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) [opensearch-cli-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cli.Command.main(Command.java:101) [opensearch-cli-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
Error: 9-08T21:50:21,345][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [smoketestnode] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: Unsupported http.type [org.opensearch.security.http.SecurityHttpServerTransport]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
Caused by: java.lang.IllegalStateException: Unsupported http.type [org.opensearch.security.http.SecurityHttpServerTransport]
	at org.opensearch.common.network.NetworkModule.getHttpServerTransportSupplier(NetworkModule.java:240) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.node.Node.newHttpTransport(Node.java:1757) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.node.Node.<init>(Node.java:911) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.node.Node.<init>(Node.java:400) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	... 6 more
```

**Comment by cwperks** [comment]
This PR is blocked by the Auto increment PR: https://github.com/opensearch-project/security/pull/3323

The bwc tests are failing because a cluster cannot be formed between 2.10 and 3.0.0 now that 2.11 exists.

**Comment by cwperks** [comment]
@RyanL1997 You may need to add the changes from https://github.com/opensearch-project/security/pull/3323 into this PR

**Review by DarshitChanpura — APPROVED** [review]

**Review by willyborankin — APPROVED** [review]

**Comment by willyborankin** [comment]
i cant merge it. no permissions

**Comment by peternied** [comment]
This is a case of a diamond dependency conflict.  I'm going to merge these changes and then backport this changes into https://github.com/opensearch-project/security/pull/3323 as @cwperks mentioned

**Pull request merged**
