### PR TITLE
Force the version of json-path 2.4.0

### PR DESCRIPTION
**Pull request by cliu123**
##  opendistro-for-elasticsearch/security pull request intake form
_Please provide as much details as possible to get feedback/acceptance on your PR quickly_

 
 1. __Category:__ (_Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation_)
 Maintenance
 
 
 2. __Github Issue # or road-map entry, if available:__

 3. __Description of changes:__

- `json-smart-2.3` is introduced by `json-path-2.4`
-  Upgrading `json-smart` to `2.4.2`. 

 4. __Why these changes are required?__ 
`json-smart` needs to be upgraded to `2.4.2` because of [this issue](https://github.com/netplex/json-smart-v1/issues/7).

 5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)
No changes in behavior

 6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manual testing_)
 UT
 
 
 7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of them_)

 8. __Is it backport from main branch?__ (_If yes, please add backport PR # and commits #_)

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by vrozov — CHANGES_REQUESTED** [review]
Please check if json-path dependency can be removed completely and only if there is no option to remove it use dependency management to enforce transient dependency version.

**Comment by cliu123** [comment]
> Please check if json-path dependency can be removed completely and only if there is no option to remove it use dependency management to enforce transient dependency version.

The dependency cannot be removed. It has multiple usages, for example: [SecuritySSLCertsInfoActionTests.java](https://github.com/opensearch-project/security/blob/4c182a216954b441cb698fe3f4d07f34a88b6d2f/src/test/java/org/opensearch/security/ssl/SecuritySSLCertsInfoActionTests.java#L55-L59), multiple places in [SecuritySSLReloadCertsActionTests.java](https://github.com/opensearch-project/security/blob/4c182a216954b441cb698fe3f4d07f34a88b6d2f/src/test/java/org/opensearch/security/ssl/SecuritySSLReloadCertsActionTests.java#L83-L86) and even more than these.

**Comment by vrozov** [comment]
@cliu123 I don't see a big problem of removing dependency on `json-path` from those 2 files. That usage is not well justified anyway and the same can be done using `jackson` library that is more commonly used. If you don't want to remove the dependency in the PR, please open new issue to remove that dependency.

**Review by vrozov — CHANGES_REQUESTED** [review]
use dependency management to enforce transient dependency version

**Comment by cliu123** [comment]
> @cliu123 I don't see a big problem of removing dependency on `json-path` from those 2 files. That usage is not well justified anyway and the same can be done using `jackson` library that is more commonly used. If you don't want to remove the dependency in the PR, please open new issue to remove that dependency.

Created an issue: https://github.com/opensearch-project/security/issues/1182

**Comment by cliu123** [comment]
> use dependency management to enforce transient dependency version

@vrozov Why enforce "transient"?

**Comment by vrozov** [comment]
@cliu123 Yes, I mean transitive, not transient.

**Comment by cliu123** [comment]
> @cliu123 Yes, I mean transitive, not transient.

Done.

**Review by vrozov — APPROVED** [review]

**Review by saratvemulapalli — APPROVED** [review]

**Pull request merged**
