### PR TITLE
backport/backport-2802-to-2.x?

### PR DESCRIPTION
**Pull request by parasjain1**
Use custom serialization in security plugin.
- Resolves https://github.com/opensearch-project/security/issues/2780

### Description
Refer https://github.com/opensearch-project/security/pull/2802

### Issues Resolved
- Resolves https://github.com/opensearch-project/security/issues/2780

Is this a backport? If so, please add backport PR # and/or commits #
Yes
https://github.com/opensearch-project/security/pull/2802

### Testing
Refer 

### Check List
- [x] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DarshitChanpura** [comment]
@parasjain1 Is this targeting 2.11 release?

**Comment by parasjain1** [comment]
@DarshitChanpura yes this is targeting 2.11 release.

**Comment by parasjain1** [comment]
FYI BWC tests are failing due to compilation failures. Seems like the recent fixes were not backported to 2.x.

* While resolving conflicts, I've not brought in any changes to the CI configuration. Please see if we need to bring those in, feel free to open a separate PR if needed. 
* I've updated the `ConfigConstants.FIRST_CUSTOM_SERIALIZATION_SUPPORTED_OS_VERSION` to `2.11.0` in this PR and accordingly also updated the versions in `SecuritySSLRequestHandlerTests`.

**Comment by cwperks** [comment]
@parasjain1 The compilation failures are due to a difference in the version of the Apache HttpClient/HttpComponent libraries used in main vs 2.x. main uses HttpClientV5 while 2.x uses HttpClientV4. This PR will need to adjust to the difference between the main and 2.x branch of the security plugin.

**Comment by cwperks** [comment]
Closing as https://github.com/opensearch-project/security/pull/3444 was merged.

**Pull request closed without merging**
