### PR TITLE
Shrink operation privileges evaluation

### PR DESCRIPTION
**Pull request by MaciejMierzwa**
### Description
Bug fix. Shrink, or resize operations weren't properly evaluated. More in the task:  https://github.com/opensearch-project/security/issues/2141

### Issues Resolved
https://github.com/opensearch-project/security/issues/2141

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by MaciejMierzwa** [comment]
I cherry-picked changes made in this [PR](https://github.com/opensearch-project/security/pull/3602) to not combine bug fix and test fix.

**Review by scrawfor99 — COMMENTED** [review]
Hi @MaciejMierzwa, just one question but otherwise looks good. 

Judging from this it looks like the issue was that the index replacer resolver was not filtering properly? Is that the change this implements which corrects the evaluation?

**Comment by MaciejMierzwa** [comment]
> Hi @MaciejMierzwa, just one question but otherwise looks good.
> 
> Judging from this it looks like the issue was that the index replacer resolver was not filtering properly? Is that the change this implements which corrects the evaluation?

Exactly. It wasn't even analyzing incoming requests. After going through that part of the code, in PriviledgesEvaluator it assumes the most restrictive access control -> As a result only user with wildcard access could perform shrink operation.

**Review by scrawfor99 — APPROVED** [review]
Looks good

**Review by cwperks — APPROVED** [review]

**Comment by cwperks** [comment]
Thank you @MaciejMierzwa . There was another case of this recently with SearchTemplateRequests too where a SearchTemplateRequest was falling through the cracks of IndexResolverReplacer and it required a user to have permissions to search all indices in order to use Search Template: https://github.com/opensearch-project/OpenSearch/pull/9122

**Pull request merged**
